### ISSUE TITLE
'Error occurred while invoking IL2CPU.' An error has occurred

### ISSUE THREAD

**Issue by ghost** [CosmosOS/Cosmos#1019]
I was working on OS development through CosmosOS, but whenever I compile (debug) it always comes back to me 'Error occurred while invoking IL2CPU.' It was only ...
Below is the compilation log, let me know if there is a way to solve this problem!

```
1>------ 빌드 시작: 프로젝트: NIOSBoot, 구성: Debug Any CPU ------
1>		Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Nixty\source\repos\NIOS\NIOS\bin\Debug\net462\NIOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Nixty\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Nixty\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Nixty\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Nixty\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Nixty\source\repos\NIOS\NIOS\bin\Debug\netstandard1.5\NIOS.dll" 
1>C:\Users\Nixty\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(39,5): error : Error occurred while invoking IL2CPU.
1>		Executing command line "C:\Users\Nixty\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Nixty\source\repos\NIOS\NIOS\bin\Debug\net462\NIOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Nixty\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Nixty\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Nixty\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Nixty\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Nixty\source\repos\NIOS\NIOS\bin\Debug\netstandard1.5\NIOS.dll" 
1>		Working directory = 'C:\Users\Nixty\source\repos\NIOS\NIOS\bin\Debug\net462\'
1>		Loaded : DebugEnabled
1>		Loaded : StackCorruptionDetectionEnabled
1>		Loaded : DebugMode
1>		Loaded : StackCorruptionDetectionLevel
1>		Loaded : TraceAssemblies
1>		Loaded : DebugCom
1>		Loaded : UseNAsm
1>		Loaded : OutputFilename
1>		Loaded : EnableLogging
1>		Loaded : EmitDebugSymbols
1>		Loaded : IgnoreDebugStubAttribute
1>		Loaded : References
1>		Loaded : AdditionalSearchDirs
1>		Loaded : AdditionalReferences
1>		Executing IL2CPU on assembly
1>		Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Object  System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(System.Object).
1>		 Called from :
1>		Microsoft.VisualBasic.CompilerServices.Conversions::System.String ToString(System.Object)
1>		NIOS.NIOS.Kernel::Void Run()
1>		Cosmos.System.Kernel::Void Run()
1>		   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 548
1>		   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 694
1>		   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
1>		   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
1>		Loaded assemblies: 
1>		C:\Users\Nixty\source\repos\NIOS\NIOS\bin\Debug\net462\Cosmos.Core.Plugs.Asm.dll
1>		C:\Users\Nixty\source\repos\NIOS\NIOS\bin\Debug\net462\Cosmos.Core.Plugs.dll
1>		C:\Users\Nixty\source\repos\NIOS\NIOS\bin\Debug\net462\Cosmos.Debug.Kernel.Plugs.Asm.dll
1>		C:\Users\Nixty\source\repos\NIOS\NIOS\bin\Debug\net462\Cosmos.System.Plugs.dll
1>		C:\Users\Nixty\source\repos\NIOS\NIOS\bin\Debug\net462\NIOS.dll
1>		Errorred
1>		IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>		IL2CPU task took 00:00:00.8170101
1>"NIOSBoot.Cosmos" 프로젝트를 빌드했습니다. - 실패
1>
========== 빌드: 성공 0, 실패 1, 최신 1, 생략 0 ==========`
```
(I'm sorry that some of the logs are written in Korean...)

For reference, I am using the latest release of CosmosOS User Kit, '2017 09 28'. I use Visual Studio version 2017 and my OS is 'Windows 7 Home Premium'. Please help me, please!

**Comment by jp2masa** [comment]
`System.Object System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(System.Object)` has to be plugged: https://github.com/dotnet/coreclr/blob/release/2.0.0/src/mscorlib/src/System/Runtime/CompilerServices/RuntimeHelpers.cs#L52.

**Comment by quajak** [comment]
What is your code, which is using `GetObjectValue`?

**Comment by antonwilc0x** [comment]
I got this problem in 20170612 to 20170928, basically all of last year, but I don't get it anymore under the new project in 20181009.
