### ISSUE TITLE
IL2CPU FileNotFoundExeption(Microsoft.CSharp)

### ISSUE THREAD

**Issue by MikaCoder** [CosmosOS/Cosmos#1126]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Compiling, IL2CPU.

#### Expected Behaviour - What do you think that should happen?
I've got no idea because it never worked.

#### Actual Behaviour - What unexpectedly happens?
1>------ Rebuild All started: Project: SimpleOS, Configuration: Debug Any CPU ------
1>SimpleOS -> C:\Users\Mika Stander\source\repos\CosmosKernel1\CosmosKernel1\bin\Debug\netcoreapp2.1\cosmos\SimpleOS.dll
1>Error : error occurred: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
1>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
1>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
1>   at Cosmos.IL2CPU.IsolatedAssemblyLoadContext..ctor(IEnumerable`1 assemblyPaths) in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\IsolatedAssemblyLoadContext.cs:line 43
1>   at Cosmos.IL2CPU.CompilerEngine..ctor(ICompilerEngineSettings aSettings) in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 96
1>   at Cosmos.IL2CPU.Program.RunCompilerEngine(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 64
1>   at Cosmos.IL2CPU.Program.Run(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in D:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 47
1>IL2CPU task took 00:00:03.9853934
1>Done building project "SimpleOS.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

#### Reproduction - How did you get this error to appear?
I don't know because i have written an Simple OS(Named SimpleOS) and it just fails to compile.
it Says something about D:\ but there is no data partition and i never had one and did not install it to USB.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit, IL2CPU

Code is on [github](https://github.com/MikaCoder/SimpleOS)

**Comment by MikaCoder** [comment]
Sorry, was an Syntax Error
