### ISSUE TITLE
Cosmos refuses to compile

### ISSUE THREAD

**Issue by VisualDevelopment** [CosmosOS/Cosmos#1151]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Devkit Installation

#### Expected Behaviour - What do you think that should happen?
Build Cosmos Devkit

#### Actual Behaviour - What unexpectedly happens?
Errors

#### Reproduction - How did you get this error to appear?
This error happens when you try to either install devkit on vs2017 and vs2019

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Devkit, latest commit

Log:

========================================
    Builder Log
========================================

========================================
    Checking Dependencies
========================================

Repos: IL2CPU, XSharp and Common is installed.
Visual Studio 15.9+ is installed.
Visual Studio Workloads is installed.
Inno Setup is installed.

========================================
    Restore - Build.sln
========================================

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" "C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln" /nologo /maxcpucount /nodeReuse:False /verbosity:minimal /t:"Restore" /p:DeployExtension=False
  Restore completed in 86.94 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Common\Cosmos.Common.csproj.
  Restore completed in 89.5 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Build.Tasks\Cosmos.Build.Tasks.csproj.
  Restore completed in 86.98 ms for C:\Users\Taxtr\Desktop\Cosmos\Common\source\Cosmos.Build.Common\Cosmos.Build.Common.csproj.
  Restore completed in 1.46 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Core\Cosmos.Core.csproj.
  Restore completed in 147.42 ms for C:\Users\Taxtr\Desktop\Cosmos\Common\source\VSPropertyPages\VSPropertyPages.csproj.
  Restore completed in 8.43 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.DebugConnectors\Cosmos.Debug.DebugConnectors.csproj.
  Restore completed in 12.23 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.Common\Cosmos.Debug.Common.csproj.
  Restore completed in 1.36 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.GDB\Cosmos.Debug.GDB.csproj.
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj : warning NU1602: Cosmos.IL2CPU does not provide an inclusive lower bound for dependency System.Reflection.Metadata. An approximate best match of System.Reflection.Metadata 1.0.21 was resolved. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj : warning NU1602: Cosmos.IL2CPU does not provide an inclusive lower bound for dependency System.Runtime.CompilerServices.Unsafe. An approximate best match of System.Runtime.CompilerServices.Unsafe 4.0.0 was resolved. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj : warning NU1602: Cosmos.IL2CPU does not provide an inclusive lower bound for dependency System.Runtime.Loader. An approximate best match of System.Runtime.Loader 4.0.0 was resolved. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj : warning NU1701: Package 'System.Reflection.Metadata 1.0.21' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
  Restore completed in 26.54 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Core_Asm\Cosmos.Core_Asm.csproj.
  Restore completed in 5.09 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.HyperVServer\Cosmos.Debug.HyperVServer.csproj.
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj : warning NU1602: Cosmos.IL2CPU does not provide an inclusive lower bound for dependency System.Reflection.Metadata. An approximate best match of System.Reflection.Metadata 1.0.21 was resolved. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj : warning NU1602: Cosmos.IL2CPU does not provide an inclusive lower bound for dependency System.Runtime.CompilerServices.Unsafe. An approximate best match of System.Runtime.CompilerServices.Unsafe 4.0.0 was resolved. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj : warning NU1602: Cosmos.IL2CPU does not provide an inclusive lower bound for dependency System.Runtime.Loader. An approximate best match of System.Runtime.Loader 4.0.0 was resolved. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj : warning NU1701: Package 'System.Reflection.Metadata 1.0.21' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
  Restore completed in 29.75 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Core_Plugs\Cosmos.Core_Plugs.csproj.
  Restore completed in 5.32 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.Hosts\Cosmos.Debug.Hosts.csproj.
  Restore completed in 1.42 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.Kernel\Cosmos.Debug.Kernel.csproj.
  Restore completed in 2.59 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Debug.Kernel.Plugs.Asm\Cosmos.Debug.Kernel.Plugs.Asm.csproj.
  Restore completed in 0.75 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Deploy.Pixie\Cosmos.Deploy.Pixie.csproj.
  Restore completed in 1.81 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.HAL2\Cosmos.HAL2.csproj.
  Restore completed in 17.42 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.Deploy.USB\Cosmos.Deploy.USB.csproj.
  Restore completed in 18.63 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.System2\Cosmos.System2.csproj.
  Restore completed in 2.57 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.System2_Plugs\Cosmos.System2_Plugs.csproj.
  Restore completed in 7.13 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.Windows\Cosmos.VS.Windows.csproj.
  Restore completed in 4.15 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\TheRingMaster\TheRingMaster.csproj.
  Restore completed in 3.02 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Tests\Cosmos.TestRunner.TestController\Cosmos.TestRunner.TestController.csproj.
  Restoring packages for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj...
  Restore completed in 2.11 ms for C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\Cosmos.Core.DebugStub\Cosmos.Core.DebugStub.csproj.
  Restoring packages for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj...
C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj : warning NU1604: Project dependency System.Reflection.Metadata does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj : warning NU1604: Project dependency System.Reflection.TypeExtensions does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj : warning NU1604: Project dependency System.Runtime.CompilerServices.Unsafe does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj : warning NU1604: Project dependency System.Runtime.Loader does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj : warning NU1701: Package 'System.Reflection.Metadata 1.0.21' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj : warning NU1701: Package 'System.Reflection.TypeExtensions 4.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
  Restore completed in 7.89 ms for C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Cosmos.IL2CPU.csproj.
  Restore completed in 1.3 ms for C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\IL2CPU.API\IL2CPU.API.csproj.
  Restore completed in 10.39 ms for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Tools\NASM\NASM.csproj.
  Restore completed in 8.72 ms for C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\IL2CPU.Debug.Symbols.csproj.
  Restore completed in 2.09 ms for C:\Users\Taxtr\Desktop\Cosmos\XSharp\source\Spruce\Spruce.csproj.
  Restore completed in 2.12 ms for C:\Users\Taxtr\Desktop\Cosmos\XSharp\source\XSharp.Assembler\XSharp.Assembler.csproj.
  Restore completed in 50.23 ms for C:\Users\Taxtr\Desktop\Cosmos\XSharp\source\XSharp.x86\XSharp.x86.csproj.
  Restore completed in 2.81 ms for C:\Users\Taxtr\Desktop\Cosmos\XSharp\source\XSharp\XSharp.csproj.
C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\IL2CPU\IL2CPU.csproj : warning NU1602: Cosmos.IL2CPU does not provide an inclusive lower bound for dependency System.Reflection.Metadata. An approximate best match of System.Reflection.Metadata 1.0.21 was resolved. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\IL2CPU\IL2CPU.csproj : warning NU1602: Cosmos.IL2CPU does not provide an inclusive lower bound for dependency System.Reflection.TypeExtensions. An approximate best match of System.Reflection.TypeExtensions 4.0.0 was resolved. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\IL2CPU\IL2CPU.csproj : warning NU1602: Cosmos.IL2CPU does not provide an inclusive lower bound for dependency System.Runtime.CompilerServices.Unsafe. An approximate best match of System.Runtime.CompilerServices.Unsafe 4.0.0 was resolved. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\IL2CPU\IL2CPU.csproj : warning NU1602: Cosmos.IL2CPU does not provide an inclusive lower bound for dependency System.Runtime.Loader. An approximate best match of System.Runtime.Loader 4.0.0 was resolved. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\IL2CPU\IL2CPU.csproj : warning NU1701: Package 'System.Reflection.Metadata 1.0.21' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\IL2CPU\IL2CPU.csproj : warning NU1701: Package 'System.Reflection.TypeExtensions 4.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
  Restore completed in 66.27 ms for C:\Users\Taxtr\Desktop\Cosmos\IL2CPU\source\IL2CPU\IL2CPU.csproj.
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj : error NU1605: Detected package downgrade: Microsoft.Data.Sqlite from 3.0.0-preview4.19216.3 to 2.0.0. Reference the package directly from the project to select a different version.  [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj : error NU1605:  Cosmos.VS.DebugEngine -> Cosmos.Build.Common -> Microsoft.Data.Sqlite (>= 3.0.0-preview4.19216.3)  [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj : error NU1605:  Cosmos.VS.DebugEngine -> Microsoft.Data.Sqlite (>= 2.0.0) [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj : error NU1605: Detected package downgrade: Microsoft.Win32.Registry from 4.6.0-preview4.19212.13 to 4.4.0. Reference the package directly from the project to select a different version.  [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj : error NU1605:  Cosmos.VS.ProjectSystem -> Cosmos.Build.Common -> Microsoft.Win32.Registry (>= 4.6.0-preview4.19212.13)  [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj : error NU1605:  Cosmos.VS.ProjectSystem -> Microsoft.Win32.Registry (>= 4.4.0) [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj : error NU1605: Detected package downgrade: Microsoft.Data.Sqlite from 3.0.0-preview4.19216.3 to 2.0.0. Reference the package directly from the project to select a different version.  [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj : error NU1605:  Cosmos.VS.DebugEngine -> IL2CPU.Debug.Symbols -> Microsoft.Data.Sqlite (>= 3.0.0-preview4.19216.3)  [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj : error NU1605:  Cosmos.VS.DebugEngine -> Microsoft.Data.Sqlite (>= 2.0.0) [C:\Users\Taxtr\Desktop\Cosmos\Cosmos\Build.sln]
  Restore failed in 1.04 sec for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.DebugEngine\Cosmos.VS.DebugEngine.csproj.
  Restore failed in 1.02 sec for C:\Users\Taxtr\Desktop\Cosmos\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj.

========================================
    Error
========================================

System.Exception: The process failed to execute!
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.WaitForExit(Process process)
   at Cosmos.Build.Builder.BuildTasks.ProcessBuildTaskBase.<>c__DisplayClass5_0.<RunAsync>b__2()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Cosmos.Build.Builder.ViewModels.MainWindowViewModel.<BuildAsync>d__27.MoveNext()

**Comment by VisualDevelopment** [comment]
Seems like a fresh clone of the repo fixed the issue.
