### ISSUE TITLE
CPU exception on VM makes VS2019 crash

### ISSUE THREAD

**Issue by EliaSulimanov** [CosmosOS/Cosmos#1334]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Compiler

#### Expected Behaviour - What do you think that should happen?
CPU exceptions on VM should not make VS2019 crush, it makes the debuging process impossible.

#### Actual Behaviour - What unexpectedly happens?
Any CPU exception that occurre on the VM, makes VS2019 crush and restart, which disconnecting the debuger from the VM

#### Reproduction - How did you get this error to appear?
Used this line, which made the CPU exception to be thrown:
`byte[] t = ByteToString.StrToByteArray("Hello World!");`
and few seconds after the CPU exception is thrown, VS2019 restarts.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20190628

**Comment by quajak** [comment]
What is the defintion of `ByteToString.StrToByteArray`? Can you please post the necessary code to reproduce this issue.

**Comment by EliaSulimanov** [comment]
ByteToString.StrToByteArray is an method provided in the Cosmos.Common namespace.
Here is the implementation of it:
https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.Common/ByteToString.cs
starting at line #9.

Here is the kernal code, hope it helps to pour some light on this issue:
`
using System;  
using System.IO;
using Cosmos.System.FileSystem;
using Cosmos.Common;
using Sys = Cosmos.System;

namespace Hello_Cosmos
{
    public class Kernel : Sys.Kernel
    {
        private static CosmosVFS cosmosVFS;
        private static readonly string rootDir = @"0:\";
`

        private bool VFSInit()
        {
            try
            {
                Console.WriteLine("VFS creation");
                cosmosVFS = new CosmosVFS();
                Console.WriteLine("VFS init");
                cosmosVFS.Initialize();
                Console.WriteLine("VFS initialized successfully");
                Sys.FileSystem.VFS.VFSManager.RegisterVFS(cosmosVFS);
                Console.WriteLine("VFS registered successfully");
            }
            catch (Exception e)
            {
                Console.WriteLine("Error occurred in VFS, more info:\n" + e.ToString());
                return false;
            }
            return true;
        }

        protected override void BeforeRun()
        {
            Console.WriteLine("Cosmos booted successfully.");

            if(!VFSInit())
            {
                Console.WriteLine("VFS fail, press any key to restart");
                Console.ReadKey(true);
                Sys.Power.Reboot();
            }

            if(File.Exists(rootDir + "log"))
            {
                var logFile = cosmosVFS.GetFile(rootDir + "log");
                Console.WriteLine("Log file size: " + logFile.mSize.ToString());
            }
            else
            {
                cosmosVFS.CreateFile(rootDir + "log");
            }

            try
            {
                byte[] t = ByteToString.StrToByteArray("Hello World!");
                var fs = Sys.FileSystem.VFS.VFSManager.GetFileStream(rootDir + "log");
                fs.Write(t, 0, t.Length);
                fs.Close();
                fs = Sys.FileSystem.VFS.VFSManager.GetFileStream(rootDir + "log");
                byte[] fr = new byte[t.Length];
                fs.Read(fr, 0, fr.Length);
                fs.Close();
                Console.WriteLine(ByteToString.ByteArrToString(fr));
            }
            catch (Exception e)
            {
                KernalException ke = new KernalException(e);
            }

            Console.WriteLine("Press any key to continue!");
            Console.ReadKey(true);
            Console.Clear();
        }

        protected override void Run()
        {
            try
            {
                mDebugger.Send("Run");
                Console.ReadKey();
            }
            catch (Exception e)
            {
                Console.WriteLine($"Got fatal exception {e.Message}");
            }
        }
    }
}
`

**Comment by quajak** [comment]
Do you get any error message from VIsual Studio when it crashes? Can you check the vs logs.

**Comment by EliaSulimanov** [comment]
VS not prompting any error and the activity log also says nothing, but in the event viewer I found this event of devenv.exe:
```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(System.String)
   at Cosmos.VS.DebugEngine.AD7Util.MessageBox(System.String, System.String)
   at Cosmos.VS.DebugEngine.AD7.Impl.AD7Process.DbgCmdMessageBox(System.String)
   at Cosmos.Debug.DebugConnectors.DebugConnector.ThreadMethod(System.Threading.CancellationToken)
   at Cosmos.Debug.DebugConnectors.DebugConnector.<Start>b__114_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

```

also, vm-player gave this log:
```
2020-05-27T12:48:36.768+03:00| vmplayer| I125: cui::VMMKS::OnVMStateChanged: alive = 1
2020-05-27T12:48:36.768+03:00| vmplayer| I125: VMMKS::CheckAndAttach: pipe name: mksctrl-0000010764-000-c366ab0e, can attach: true, is remoting: false.
2020-05-27T12:48:36.790+03:00| vmplayer| I125: SOCKET 3 (2340) AsyncTCPSocketSetOption: Option layer/level [6], option/name [1]: successfully set OS option for TCP socket.
2020-05-27T12:48:36.809+03:00| vmplayer| I125: cui::MKSScreenWindowCoordinator::HandleGuestTopologyChange: main UI rect: 714x568 @ 130,130
2020-05-27T12:48:36.809+03:00| vmplayer| I125: cui::MKSScreenWindowCoordinator::HandleGuestTopologyChange: Found 1 present screens
2020-05-27T12:48:36.809+03:00| vmplayer| I125: cui::MKSScreenWindowCoordinator::HandleGuestTopologyChange: Windows for extra guest monitors will not be shown
2020-05-27T12:48:36.840+03:00| vmplayer| I125: VMHSGetDataFileKey: Could not get the dataFileKey from VMDB
2020-05-27T12:48:37.742+03:00| vmplayer| I125: VMHSGetDataFileKey: Could not get the dataFileKey from VMDB
2020-05-27T12:48:38.237+03:00| vmplayer| I125: cui::MKSScreenWindowCoordinator::HandleGuestTopologyChange: main UI rect: 656x552 @ 130,130
2020-05-27T12:48:38.237+03:00| vmplayer| I125: cui::MKSScreenWindowCoordinator::HandleGuestTopologyChange: Found 1 present screens
2020-05-27T12:48:38.237+03:00| vmplayer| I125: cui::MKSScreenWindowCoordinator::HandleGuestTopologyChange: Windows for extra guest monitors will not be shown
2020-05-27T12:50:40.543+03:00| vmplayer| I125: VMHSGetDataFileKey: Could not get the dataFileKey from VMDB
2020-05-27T12:50:52.957+03:00| vmplayer| I125: DlgUI: How do you want to close the virtual machine?
2020-05-27T12:50:52.957+03:00| vmplayer| I125+ Suspending will preserve your environment and data for later use.
2020-05-27T12:50:52.957+03:00| vmplayer| I125+ If powering off, make sure that the virtual machine is in a safe state for shutdown.
2020-05-27T12:50:52.957+03:00| vmplayer| I125+ 
2020-05-27T12:50:55.254+03:00| vmplayer| I125: VigorOnlineRpcDemux Deferring completion on /vm/#0e03331e596b984a/vmx/vigor/cmd/##19/
2020-05-27T12:50:55.300+03:00| vmplayer| W115: SOCKET 2 (-1) AsyncNamedPipeRecvCallback: failed to get overlapped result: 109.
2020-05-27T12:50:55.300+03:00| vmplayer| W115: MKSControlClient: Remote Disconnect: socket closed: (4) Remote disconnected.
2020-05-27T12:50:55.300+03:00| vmplayer| W115: MKSControlClient: MKSControlWriteCB returns because connection is invalid: mSocket = 6B6F900, mConState = 0.
2020-05-27T12:50:55.300+03:00| vmplayer| I125: MKSControlClient: Disconnect is called.
2020-05-27T12:50:55.300+03:00| vmplayer| W115: MKSControlClient: MKSControlWriteCB returns because connection is invalid: mSocket = 0, mConState = 0.
2020-05-27T12:50:55.316+03:00| vmplayer| I125: wui::MKSScreenView::Uninitialize.
2020-05-27T12:50:55.316+03:00| vmplayer| I125: cui::MKSScreenView::SetRenderTarget: hostWindow and surfaceID are none. id: 0. 
2020-05-27T12:50:55.316+03:00| vmplayer| I125: cui::MKSScreenView::OnHostWindowChanged, id: 0, unsetting destination and setting is rendering to false
2020-05-27T12:50:55.675+03:00| vmplayer| I125: Vix: [foundryVMPowerOps.c:988]: FoundryVMPowerStateChangeCallback: C:\Users\ielia\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\Debug.vmx, vmx/execState/val = poweredOff.
2020-05-27T12:50:55.675+03:00| vmplayer| I125: C:\Users\ielia\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\Debug.vmx: Disconnect check in progress.
2020-05-27T12:50:55.675+03:00| vmplayer| I125: C:\Users\ielia\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\Debug.vmx: Disconnect check: no reasons to stay connected.
2020-05-27T12:50:55.675+03:00| vmplayer| I125: VigorOnlineDisconnect: disconnect /vm/#0e03331e596b984a/ via /db/connection/#a/
2020-05-27T12:50:55.675+03:00| vmplayer| I125: C:\Users\ielia\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\Debug.vmx: Unmounting VM begun.
2020-05-27T12:50:55.675+03:00| vmplayer| I125: VMDB unmount initiated for /vm/#0e03331e596b984a/.
2020-05-27T12:50:55.675+03:00| vmplayer| I125: VmdbPipeStreamsOvlError Couldn't read: (109) The pipe has been ended.
2020-05-27T12:50:55.675+03:00| vmplayer| I125: VmdbCnxDisconnect: Disconnect: closed pipe for sub cnx '/db/connection/#a/' (-32)
2020-05-27T12:50:55.675+03:00| vmplayer| I125: VigorOnlineUnmountCb: Mount state values have changed for /vm/#0e03331e596b984a/.
2020-05-27T12:50:55.675+03:00| vmplayer| I125: VmdbDbRemoveCnx: Removing Cnx from Db for '/db/connection/#a/'
2020-05-27T12:50:55.675+03:00| vmplayer| I125: VigorOnlineUnmountCb: Unmount complete for /vm/#0e03331e596b984a/.
2020-05-27T12:50:55.675+03:00| vmplayer| I125: VigorOnlineUnmountCb unset Vigor path on vm unmount.
2020-05-27T12:50:55.675+03:00| vmplayer| I125: C:\Users\ielia\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\Debug.vmx: Unmounting VM complete.
2020-05-27T12:50:55.675+03:00| vmplayer| I125: Win32U_GetFileAttributes: GetFileAttributesExW("C:\Users\ielia\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\Debug.vmpl", ...) failed, error: 2
2020-05-27T12:50:55.675+03:00| vmplayer| I125: C:\Users\ielia\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\Debug.vmx: Reloading config state.
2020-05-27T12:50:55.722+03:00| vmplayer| I125: VMHS: Transitioned vmx/execState/val to poweredOff
2020-05-27T12:50:55.738+03:00| vigorCnx| I125: VigorOfflineGetToolsVersion: updated tools version to 0
2020-05-27T12:50:55.738+03:00| vmplayer| I125: Vix: [foundryVMPowerOps.c:988]: FoundryVMPowerStateChangeCallback: C:\Users\ielia\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\Debug.vmx, vmx/execState/val = poweredOff.
2020-05-27T12:50:55.785+03:00| vmplayer| I125: VMMKS::OnMKSDeviceInfoChanged: reset pipe name now in offline.
2020-05-27T12:50:55.785+03:00| vmplayer| I125: SOCKET 3 (2340) send error 10054: An existing connection was forcibly closed by the remote host
2020-05-27T12:50:55.785+03:00| vmplayer| I125: Detected automation socket close for VM (C:\Users\ielia\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation\Debug.vmx)
2020-05-27T12:50:55.800+03:00| vmplayer| I125: cui::VMMKS::OnVMStateChanged: alive = 0
2020-05-27T12:50:55.800+03:00| vmplayer| I125: cui::VMMKS::OnVMStateChanged: alive = 0
2020-05-27T12:50:55.816+03:00| vmplayer| I125: VMHSGetDataFileKey: Could not get the dataFileKey from VMDB
2020-05-27T12:50:55.832+03:00| vmplayer| I125: PlayerApp::OnVMPoweredOff
2020-05-27T12:50:55.832+03:00| vmplayer| I125: VMMgr::CloseVM: closing VM at /vm/#0e03331e596b984a/
2020-05-27T12:50:55.863+03:00| vmplayer| I125: VMMgr::OnVMDestroyed: cleaning up after destroyed VM at /vm/#0e03331e596b984a/
2020-05-27T12:50:55.863+03:00| vmplayer| I125: MKSWindowTrans: The current transaction 6CF26F8 has not been submitted.
2020-05-27T12:50:55.863+03:00| vmplayer| I125: MKSControlClient: Disconnect is called.
2020-05-27T12:50:55.863+03:00| vmplayer| W115: MKSControlClient: MKSControlWriteCB returns because connection is invalid: mSocket = 0, mConState = 0.
2020-05-27T12:50:56.647+03:00| vmplayer| I125: CDS: Clearing the credentials cache.
2020-05-27T12:50:56.647+03:00| usbCCIDEnumCards| I125: USB-CCID: Card enum thread exiting.
2020-05-27T12:50:56.647+03:00| vmplayer| I125: WORKER: asyncOps=0 maxActiveOps=0 maxPending=0 maxCompleted=0
2020-05-27T12:50:56.709+03:00| vmplayer| I125: Clean exit.

```


The time between 12:48 to 12:50 is the time I waited before stepping into the "byte[] t" line, so the vm-log would be easier to read.
Hope this helps
