### ISSUE TITLE
VMWare says: loading... <myos>.bin Failed! tried recompiling

### ISSUE THREAD

**Issue by LosSkillos** [CosmosOS/Cosmos#1337]
#### Area of Cosmos - What area of Cosmos are we dealing with?
deployment

#### Expected Behaviour - What do you think that should happen?
My os should get started

#### Actual Behaviour - What unexpectedly happens?
This: 
loading.... myos..bin Failed!
and then types
boot:

#### Reproduction - How did you get this error to appear?
by launching the os in vmware

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos Userkit C#

By the way vmware set to ms-dos

Also when after the build finishes i get this:
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Unexpected exception during Attach

System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

File name: 'System.Reflection.TypeExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

   at DapperExtensions.DapperExtensionsConfiguration.<>c__DisplayClass19_0.<GetMapType>b__0(Assembly a)

   at DapperExtensions.DapperExtensionsConfiguration.GetMapType(Type entityType)

   at DapperExtensions.DapperExtensionsConfiguration.GetMap(Type entityType)

   at DapperExtensions.DapperExtensionsConfiguration.GetMap[T]()

   at DapperExtensions.DapperImplementor.GetList[T](DbConnection connection, Object predicate, IList`1 sort, DbTransaction transaction, Nullable`1 commandTimeout, Boolean buffered)

   at DapperExtensions.DapperExtensions.GetList[T](DbConnection connection, Object predicate, IList`1 sort, DbTransacti......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by quajak** [comment]
Is this the same issue as https://github.com/CosmosOS/Cosmos/issues/1332?

**Comment by LosSkillos** [comment]
I increased ram to 64mb and it works.
