### ISSUE TITLE
VS2019 crash when trying to open the debugger "locals" tab

### ISSUE THREAD

**Issue by EliaSulimanov** [CosmosOS/Cosmos#1346]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Debugger

#### Expected Behaviour - What do you think that should happen?
Expect to see all the local variables on the locals tab in VS2019 in time of debug

#### Actual Behaviour - What unexpectedly happens?
VS2019 crash when you try to open the "locals" tab while debugging

#### Reproduction - How did you get this error to appear?
Put breakpoint in your code, try to go to the "locals" tab as you reach the breakpoint.
No error is prompted.
devenv.exe event at the event viewer says:
```
Description: The application requested process termination through System.Environment.FailFast(string message).
Stack:
   at Microsoft.VisualStudio.Shell.Interop.IVsWindowFrameNotify3.OnShow(Int32)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame+<>c__DisplayClass525_0.<NotifyOnShow>b__0()
   at Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(System.Func`1<Int32>, Boolean, Boolean)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.NotifyOnShow(Int32)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.OnContentShowing(Microsoft.VisualStudio.PlatformUI.Shell.View)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.OnViewContentShowing(System.Object, Microsoft.VisualStudio.PlatformUI.Shell.Controls.ViewEventArgs)
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at System.Windows.RoutedEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at Microsoft.VisualStudio.PlatformUI.Shell.Controls.ViewPresenter.<AsyncRaiseEvent>b__12_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?

User Kit 20190628

**Comment by Kiirx** [comment]
Can be closed
