### ISSUE TITLE
CS2019 crash when putting breakpoint on previos vm-player crashing line

### ISSUE THREAD

**Issue by homecat1** [CosmosOS/Cosmos#1348]
#### Area of Cosmos - What area of Cosmos are we dealing with?
IDE

#### Expected Behaviour - What do you think that should happen?
Expecing VS2019 not to crash but run the dubgger normally

#### Actual Behaviour - What unexpectedly happens?
VS2019 crashing and restarts

#### Reproduction - How did you get this error to appear?

1. I used this line to let VM-player crash:
`throw new Exception("test");`
2. I put breakpoint on this line and run the project again.
3. VS2019 crash and restart.

devenv.exe event:
```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(System.String)
   at Cosmos.VS.DebugEngine.AD7Util.MessageBox(System.String, System.String)
   at Cosmos.VS.DebugEngine.AD7.Impl.AD7Process.DbgCmdMessageBox(System.String)
   at Cosmos.Debug.DebugConnectors.DebugConnector.ThreadMethod(System.Threading.CancellationToken)
   at Cosmos.Debug.DebugConnectors.DebugConnector.<Start>b__114_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

#1338 would probably fix it.

Notice it differs from #1334 by the fact that no CPU exception was thrown.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 20190628

**Comment by Kiirx** [comment]
Can be closed if fixed, I've never seen anybody using breakpoints tho

**Comment by quajak** [comment]
The Visual Studio extension is quite broken currently and part of it is that breakpoints dont work

**Comment by AsertCreator** [comment]
I don't think Cosmos supports breakpoints

**Comment by Kiirx** [comment]
> I don't think Cosmos supports breakpoints

if we talk about breakpoints its because cosmos does

**Comment by EliaSulimanov** [comment]
If it's unfixable from our end, can be closed.

**Comment by quajak** [comment]
I think its a bug with the cosmos debugger extension since they worked in the past and can be fixed, if someone puts in the work.

**Comment by valentinbreiz** [comment]
Cosmos Gen3 has replaced the IL2CPU-based Gen2 codebase, and `gen3` is now the default branch of this repository. This issue was filed against Gen2, which is no longer developed, so it is being closed as part of the Gen3 cutover (#3088).

If you still hit this on Gen3, please open a fresh issue. The compiler, the build pipeline and the debugging story are all different now, so a new report will get a far more useful answer than reviving this one. Start here: https://cosmosos.github.io/

Gen2 remains on the `gen2` branch, and this issue stays readable.
