### ISSUE TITLE
Could not load type 'Cosmos.Debug.Kernel.DebuggerFactory' from assembly 'Cosmos.Debug.Kernel'

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#1581]
**Exception**
```
1>Message: Checking target assembly: C:\Users\valentinbreiz\source\repos\CosmosKernel2\CosmosKernel2\bin\Debug\netcoreapp2.0\cosmos\CosmosKernel2.dll
1>IL2CPU : error : Exception: System.TypeLoadException: Could not load type 'Cosmos.Debug.Kernel.DebuggerFactory' from assembly 'Cosmos.Debug.Kernel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983'.
1>   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
1>   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
1>   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
1>   at System.Reflection.RuntimeModule.ResolveMethod(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
1>   at Cosmos.IL2CPU.ILReader.ProcessMethod(MethodBase aMethod) in A:\Computer\Documents\GitHub\IL2CPU\source\Cosmos.IL2CPU\ILReader.cs:line 363
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in A:\Computer\Documents\GitHub\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 639
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in A:\Computer\Documents\GitHub\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 770
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in A:\Computer\Documents\GitHub\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 264
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in A:\Computer\Documents\GitHub\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:00.7941197
```

**To Reproduce**
Create a new kernel with last devkit.

**Context**
- [x] Both Cosmos VS Extensions are installed
- [x] The Cosmos nuget packages are installed

**Comment by quajak** [comment]
Most likely it is still using an old version of `Cosmos.Debug.Kernel`. Can you try build `Cosmos.Debug.Kernel` manually and replace the dll in Cosmos User Kit.

**Comment by valentinbreiz** [comment]
I tried to rebuild the devkit after updating Visual Studio to 16.8.2 and it's even worse lol

I have errors everyone with dependencies:
```
Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core.	
```

![image](https://user-images.githubusercontent.com/18724279/100943146-f6166d80-34fc-11eb-9d22-0fcfa00be258.png)


And I have the same error when I try to build the solution:
```
Build started...
1>------ Build started: Project: CosmosKernel3, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>CosmosKernel3 -> C:\Users\valentinbreiz\source\repos\CosmosKernel3\CosmosKernel3\bin\Debug\netcoreapp2.0\cosmos\CosmosKernel3.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\valentinbreiz\source\repos\CosmosKernel3\CosmosKernel3\bin\Debug\netcoreapp2.0\cosmos\CosmosKernel3.dll
1>IL2CPU : error : Exception: System.TypeLoadException: Could not load type 'Cosmos.Debug.Kernel.DebuggerFactory' from assembly 'Cosmos.Debug.Kernel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983'.
1>   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
1>   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
1>   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
1>   at System.Reflection.RuntimeModule.ResolveMethod(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
1>   at Cosmos.IL2CPU.ILReader.ProcessMethod(MethodBase aMethod) in A:\Computer\Documents\GitHub\IL2CPU\source\Cosmos.IL2CPU\ILReader.cs:line 363
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in A:\Computer\Documents\GitHub\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 639
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in A:\Computer\Documents\GitHub\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 770
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in A:\Computer\Documents\GitHub\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 264
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in A:\Computer\Documents\GitHub\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:01.0587096
1>Done building project "CosmosKernel3.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by quajak** [comment]
Can you update the nuget packages? 

`Project is targeting runtime 'cosmos' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core.` shouldnt actually prevent anything from building.

**Comment by valentinbreiz** [comment]
Since we find out what causes the issue (https://github.com/CosmosOS/Cosmos/issues/1588), I close this
