### ISSUE TITLE
Generics don't seem to work

### ISSUE THREAD

**Issue by Shadowblitz16** [CosmosOS/Cosmos#1618]
Generics don't seem to work at all in Cosmos in CosmosUserKit-20200708-vs2019.

I am on windows 10 pro 64 bit using vs community 2019.

doing this..
```
        public  void Register<T>(string id) where T : Command
        {
            commands.Add(id, (T)Activator.CreateInstance(typeof(T), id));
        }
```

or having this...
```
        public IEnumerator<Command> GetEnumerator()
        {
            return commands.Values.GetEnumerator();
        }
````

seems to crash the os or make it not compile.

here is the base of the project right now...
```cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;

namespace Os95.Commands
{
    public abstract class Command
    {

        string         _id;
        CommandManager _manager;

        public string          GetID() => _id;
        public abstract string GetDesc();
        public abstract void   Execute(string[] args);

        protected CommandManager Manager => _manager;

        public Command(CommandManager manager, string id)
        {
            _id      = id.ToUpper();
            _manager = manager;
        }
    }

    public class CommandManager : IEnumerable<Command>
    {
        Dictionary<string, Command> commands = new Dictionary<string, Command>();

        public void Execute(string command)
        {
            var str = command.Split(' ');
            var id = str[0].ToUpper();

            if (str.Length > 0)
            {
                if (commands.ContainsKey(id))
                {
                    var args = new string[str.Length - 2];
                    Array.Copy(str, 1, args, 0, args.Length);

                    commands[id].Execute(args);
                }
                else
                {
                    Console.WriteLine("Command " + id + " does not exist. Type HELP for more info");
                }
            }
            else
            {
                Console.WriteLine("Command " + id + " does not exist. Type HELP for more info");
            }
        }


        public  void Register<T>(string id) where T : Command
        {
            commands.Add(id, (T)Activator.CreateInstance(typeof(T), id));
        }

        public IEnumerator<Command> GetEnumerator()
        {
            return commands.Values.GetEnumerator();
        }


        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }
}
```

**Comment by quajak** [comment]
A bit more information than crash/cant compile would make it possible to help (Logs and/or error messages). Cosmos does not currently support Reflection, which might be the cause of this problem.

**Comment by Shadowblitz16** [comment]
[Os95.zip](https://github.com/CosmosOS/Cosmos/files/5762165/Os95.zip)
first error is this..
```cs
1>------ Build started: Project: Os95, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>Os95 -> C:\Users\Shadowblitz16\Documents\Projects\Cs\Os95\Os95\bin\Debug\netcoreapp2.0\cosmos\Os95.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\Shadowblitz16\Documents\Projects\Cs\Os95\Os95\bin\Debug\netcoreapp2.0\cosmos\Os95.dll
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Boolean  System.RuntimeTypeHandle.IsComObject(System.RuntimeType, System.Boolean).
1>  Called from :
1>System.RuntimeType::Boolean IsGenericCOMObjectImpl()
1>System.RuntimeType::System.Object CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[], System.Threading.StackCrawlMark ByRef)
1>System.Activator::System.Object CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
1>System.Activator::System.Object CreateInstance(System.Type, System.Object[])
1>Os95.Commands.CommandManager::Void Register[CommandHelp](System.String)
1>Os95.Kernel::Void BeforeRun()
1>Cosmos.System.Kernel::Void BeforeRun()
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 617
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 770
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 264
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:03.8868357
1>Done building project "Os95.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

if you remove the generic command registration then it compiles and runs but when you type in the command it errors and crashes visual studio.

**Comment by quajak** [comment]
This plug will most likely be added by #1099 until then you can either add the plug yourself or take a different approach.
