### ISSUE TITLE
Exception: System.InvalidOperationException: Value must be set.

### ISSUE THREAD

**Issue by tarithj** [CosmosOS/Cosmos#1625]
**Exception**
Exception: System.InvalidOperationException: Value must be set.

** VS Output Logs **
```
1>------ Build started: Project: mag, Configuration: Debug Any CPU ------
1>mag -> C:\Users\DELL\source\repos\mag\bin\Debug\netcoreapp2.0\cosmos\mag.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\DELL\source\repos\mag\bin\Debug\netcoreapp2.0\cosmos\mag.dll
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.LOCAL_ARGUMENT_INFO'
1>IL2CPU : error : Exception: System.InvalidOperationException: Value must be set.
1>   at Microsoft.Data.Sqlite.SqliteParameter.Bind(sqlite3_stmt stmt)
1>   at Microsoft.Data.Sqlite.SqliteParameterCollection.Bind(sqlite3_stmt stmt)
1>   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
1>   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
1>   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
1>   at IL2CPU.Debug.Symbols.SqliteBulkCopy.WriteToServer(IDataReader reader) in C:\Development\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\SqliteBulkCopy.cs:line 66
1>   at IL2CPU.Debug.Symbols.DebugInfo.BulkInsert[T](String aTableName, IList`1 aList, Int32 aFlushSize, Boolean aFlush) in C:\Development\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\DebugInfo.cs:line 514
1>   at IL2CPU.Debug.Symbols.DebugInfo.WriteAllLocalsArgumentsInfos(IList`1 aInfos) in C:\Development\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\DebugInfo.cs:line 436
1>   at Cosmos.IL2CPU.AppAssembler.FinalizeDebugInfo() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 431
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 209
1>IL2CPU task took 00:00:07.7624091
1>Done building project "mag.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

Heres the [code](https://www.dropbox.com/s/a8kx6nginpfdbsr/mag.zip?dl=0)

**Comment by WeirdPerson420** [comment]
Did you ever fix this issue because I'm facing it as well
