### ISSUE TITLE
Dev Kit Build Errors: Kernel Not Found Build Failed....

### ISSUE THREAD

**Issue by elkaamee326** [CosmosOS/Cosmos#1669]
** VS Output Logs **
Post the entire output log given by Visual Studio for the build
```1>------ Build started: Project: Spruce, Configuration: Debug Any CPU ------
2>------ Build started: Project: IL2CPU.API, Configuration: Debug Any CPU ------
2>IL2CPU.API -> C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\IL2CPU.API\bin\Debug\netstandard2.0\IL2CPU.API.dll
2>IL2CPU : error : No kernel found.
2>Message: Executing IL2CPU on assembly
2>Message: Kernel Base: Cosmos.System.Kernel
2>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\IL2CPU.API\bin\Debug\netstandard2.0\IL2CPU.API.dll
2>IL2CPU task took 00:00:03.0063621
2>Done building project "IL2CPU.API.csproj" -- FAILED.
3>------ Build started: Project: Cosmos.Common, Configuration: Debug Any CPU ------
1>Spruce -> C:\Users\elkaa\Desktop\Source\Cosmos\XSharp\source\Spruce\bin\Debug\netstandard2.0\Spruce.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\XSharp\source\Spruce\bin\Debug\netstandard2.0\Spruce.dll
1>IL2CPU : error : No kernel found.
1>IL2CPU task took 00:00:01.9914820
1>Done building project "Spruce.csproj" -- FAILED.
4>------ Build started: Project: Cosmos.Core, Configuration: Debug Any CPU ------
3>Cosmos.Common -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.Common\bin\Debug\netstandard2.0\Cosmos.Common.dll
3>Message: Executing IL2CPU on assembly
3>IL2CPU : error : No kernel found.
3>Message: Kernel Base: Cosmos.System.Kernel
3>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.Common\bin\Debug\netstandard2.0\Cosmos.Common.dll
3>IL2CPU task took 00:00:01.0495077
3>Done building project "Cosmos.Common.csproj" -- FAILED.
5>------ Build started: Project: IL2CPU.Debug.Symbols, Configuration: Debug Any CPU ------
5>C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\DebugSymbolReader.cs(169,30,169,32): warning CS0168: The variable 'ex' is declared but never used
5>C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\DebugInfo.cs(54,24,54,31): warning CS0169: The field 'DebugInfo.mDbName' is never used
5>IL2CPU.Debug.Symbols -> C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\bin\Debug\netstandard2.0\IL2CPU.Debug.Symbols.dll
5>Message: Executing IL2CPU on assembly
5>IL2CPU : error : No kernel found.
5>Message: Kernel Base: Cosmos.System.Kernel
5>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\bin\Debug\netstandard2.0\IL2CPU.Debug.Symbols.dll
5>IL2CPU task took 00:00:05.4293764
5>Done building project "IL2CPU.Debug.Symbols.csproj" -- FAILED.
6>------ Build started: Project: Cosmos.Build.Common, Configuration: Debug Any CPU ------
6>C:\Users\elkaa\Desktop\Source\Cosmos\Common\source\Cosmos.Build.Common\BochsSupport.cs(76,30,76,32): warning CS0168: The variable 'ex' is declared but never used
6>Cosmos.Build.Common -> C:\Users\elkaa\Desktop\Source\Cosmos\Common\source\Cosmos.Build.Common\bin\Debug\netstandard2.0\Cosmos.Build.Common.dll
6>Message: Executing IL2CPU on assembly
6>IL2CPU : error : No kernel found.
6>Message: Kernel Base: Cosmos.System.Kernel
6>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\Common\source\Cosmos.Build.Common\bin\Debug\netstandard2.0\Cosmos.Build.Common.dll
6>IL2CPU task took 00:00:04.1176438
6>Done building project "Cosmos.Build.Common.csproj" -- FAILED.
7>------ Build started: Project: XSharp, Configuration: Debug Any CPU ------
4>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.Core\INTs.cs(235,29,235,46): warning CS0649: Field 'INTs.mLastKnownAddress' is never assigned to, and will always have its default value 0
4>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.Core\ACPI.cs(89,30,89,36): warning CS0414: The field 'ACPI.SCI_EN' is assigned but its value is never used
4>Cosmos.Core -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.Core\bin\Debug\netstandard2.0\Cosmos.Core.dll
4>Message: Executing IL2CPU on assembly
4>IL2CPU : error : No kernel found.
4>Message: Kernel Base: Cosmos.System.Kernel
4>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.Core\bin\Debug\netstandard2.0\Cosmos.Core.dll
4>IL2CPU task took 00:00:02.7542907
4>Done building project "Cosmos.Core.csproj" -- FAILED.
8>------ Build started: Project: Cosmos.Core.DebugStub, Configuration: Debug Any CPU ------
8>Cosmos.Core.DebugStub -> C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.Core.DebugStub\bin\Debug\netstandard2.0\Cosmos.Core.DebugStub.dll
8>Message: Executing IL2CPU on assembly
8>IL2CPU : error : No kernel found.
8>Message: Kernel Base: Cosmos.System.Kernel
8>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.Core.DebugStub\bin\Debug\netstandard2.0\Cosmos.Core.DebugStub.dll
8>IL2CPU task took 00:00:02.9484386
8>Done building project "Cosmos.Core.DebugStub.csproj" -- FAILED.
9>------ Build started: Project: Cosmos.HAL2, Configuration: Debug Any CPU ------
7>XSharp -> C:\Users\elkaa\Desktop\Source\Cosmos\XSharp\source\XSharp\XSharp\bin\Debug\netstandard2.0\XSharp.dll
7>Message: Executing IL2CPU on assembly
7>Message: Kernel Base: Cosmos.System.Kernel
7>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\XSharp\source\XSharp\XSharp\bin\Debug\netstandard2.0\XSharp.dll
7>IL2CPU : error : No kernel found.
7>IL2CPU task took 00:00:02.6469301
7>Done building project "XSharp.csproj" -- FAILED.
10>------ Build started: Project: Cosmos.IL2CPU, Configuration: Debug Any CPU ------
9>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.HAL2\PCIDeviceBridge.cs(13,21,13,39): warning CS0108: 'PCIDeviceBridge.SecondaryBusNumber' hides inherited member 'PCIDevice.SecondaryBusNumber'. Use the new keyword if hiding was intended.
9>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.HAL2\BlockDevice\Ports\Satapi.cs(105,21,105,27): warning CS0162: Unreachable code detected
9>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.HAL2\BlockDevice\Ports\Sata.cs(112,21,112,27): warning CS0162: Unreachable code detected
9>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.HAL2\BlockDevice\Ports\Sata.cs(206,21,206,27): warning CS0162: Unreachable code detected
9>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.HAL2\BlockDevice\Ports\Sata.cs(280,21,280,27): warning CS0162: Unreachable code detected
9>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.HAL2\Drivers\Video\VGADriver.cs(828,20,828,26): warning CS0219: The variable 'values' is assigned but its value is never used
9>Cosmos.HAL2 -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.HAL2\bin\Debug\netstandard2.0\Cosmos.HAL2.dll
9>IL2CPU : error : No kernel found.
9>Message: Executing IL2CPU on assembly
9>Message: Kernel Base: Cosmos.System.Kernel
9>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.HAL2\bin\Debug\netstandard2.0\Cosmos.HAL2.dll
9>IL2CPU task took 00:00:01.3203669
9>Done building project "Cosmos.HAL2.csproj" -- FAILED.
11>------ Build started: Project: Cosmos.HAL, Configuration: Debug Any CPU ------
11>Cosmos.HAL -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\30-HAL\Cosmos.HAL\bin\Debug\netstandard2.0\Cosmos.HAL.dll
11>Message: Executing IL2CPU on assembly
11>Message: Kernel Base: Cosmos.System.Kernel
11>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\30-HAL\Cosmos.HAL\bin\Debug\netstandard2.0\Cosmos.HAL.dll
11>IL2CPU : error : No kernel found.
11>IL2CPU task took 00:00:01.8587311
11>Done building project "Cosmos.HAL.csproj" -- FAILED.
12>------ Build started: Project: Cosmos.CPU.x86, Configuration: Debug Any CPU ------
10>Cosmos.IL2CPU -> C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\bin\Debug\netstandard2.0\Cosmos.IL2CPU.dll
12>Cosmos.CPU.x86 -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\10-CPU\Cosmos.CPU.x86\bin\Debug\netstandard2.0\Cosmos.CPU.x86.dll
12>Message: Executing IL2CPU on assembly
12>Message: Kernel Base: Cosmos.System.Kernel
12>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\10-CPU\Cosmos.CPU.x86\bin\Debug\netstandard2.0\Cosmos.CPU.x86.dll
12>IL2CPU : error : No kernel found.
12>IL2CPU task took 00:00:01.9453567
12>Done building project "Cosmos.CPU.x86.csproj" -- FAILED.
13>------ Build started: Project: Cosmos.System, Configuration: Debug Any CPU ------
10>Error : error occurred: System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
10>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
10>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
10>   at Cosmos.IL2CPU.IsolatedAssemblyLoadContext..ctor(IEnumerable`1 assemblyPaths) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\IsolatedAssemblyLoadContext.cs:line 43
10>   at Cosmos.IL2CPU.CompilerEngine..ctor(ICompilerEngineSettings aSettings) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 96
10>   at Cosmos.IL2CPU.Program.RunCompilerEngine(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 64
10>   at Cosmos.IL2CPU.Program.Run(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 47
10>IL2CPU task took 00:00:03.7160650
10>Done building project "Cosmos.IL2CPU.csproj" -- FAILED.
14>------ Build started: Project: Cosmos.System2, Configuration: Debug Any CPU ------
13>Cosmos.System -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\40-System\Cosmos.System\bin\Debug\netstandard2.0\Cosmos.System.dll
13>IL2CPU : error : No kernel found.
13>Message: Executing IL2CPU on assembly
13>Message: Kernel Base: Cosmos.System.Kernel
13>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\40-System\Cosmos.System\bin\Debug\netstandard2.0\Cosmos.System.dll
13>IL2CPU task took 00:00:01.3739836
13>Done building project "Cosmos.System.csproj" -- FAILED.
15>------ Build started: Project: Cosmos.Core_Asm, Configuration: Debug Any CPU ------
14>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2\Network\IPV4\ICMPClient.cs(108,1,108,1): warning CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'param'.'
14>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2\Network\IPV4\UDP\DHCP\DHCPClient.cs(23,13,23,14): warning CS1570: XML comment has badly formed XML -- 'End tag was not expected at this location.'
14>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2\Network\IPV4\UDP\DHCP\DHCPClient.cs(50,1,50,1): warning CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'param'.'
14>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2\Network\IPV4\UDP\DNS\DNSClient.cs(66,1,66,1): warning CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'param'.'
14>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2\PCSpeaker.cs(37,24,37,29): warning CS1584: XML comment has syntactically incorrect cref attribute 'https://en.wikipedia.org/wiki/Duration_(music)'
14>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2\PCSpeaker.cs(52,24,52,29): warning CS1584: XML comment has syntactically incorrect cref attribute 'https://en.wikipedia.org/wiki/Musical_note'
14>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2\PCSpeaker.cs(53,24,53,29): warning CS1584: XML comment has syntactically incorrect cref attribute 'https://en.wikipedia.org/wiki/Audio_frequency'
14>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2\Network\Config\IPConfig.cs(142,50,142,51): warning CS0162: Unreachable code detected
14>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2\Graphics\VBECanvas.cs(84,9,84,10): warning CS1587: XML comment is not placed on a valid language element
14>Cosmos.System2 -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2\bin\Debug\netstandard2.0\Cosmos.System2.dll
14>IL2CPU : error : No kernel found.
14>Message: Executing IL2CPU on assembly
14>Message: Kernel Base: Cosmos.System.Kernel
14>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2\bin\Debug\netstandard2.0\Cosmos.System2.dll
14>IL2CPU task took 00:00:01.7175227
14>Done building project "Cosmos.System2.csproj" -- FAILED.
16>------ Build started: Project: Cosmos.Platform.PC, Configuration: Debug Any CPU ------
15>Cosmos.Core_Asm -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.Core_Asm\bin\Debug\netstandard2.0\Cosmos.Core_Asm.dll
16>Cosmos.Platform.PC -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\20-Platform\Cosmos.Platform.PC\bin\Debug\netstandard2.0\Cosmos.Platform.PC.dll
15>Error : error occurred: System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
15>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
15>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
15>   at Cosmos.IL2CPU.IsolatedAssemblyLoadContext..ctor(IEnumerable`1 assemblyPaths) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\IsolatedAssemblyLoadContext.cs:line 43
15>   at Cosmos.IL2CPU.CompilerEngine..ctor(ICompilerEngineSettings aSettings) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 96
15>   at Cosmos.IL2CPU.Program.RunCompilerEngine(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 64
15>   at Cosmos.IL2CPU.Program.Run(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 47
15>IL2CPU task took 00:00:04.1118628
15>Done building project "Cosmos.Core_Asm.csproj" -- FAILED.
17>------ Build started: Project: Cosmos.Debug.Kernel.Plugs.Asm, Configuration: Debug Any CPU ------
16>IL2CPU : error : No kernel found.
16>Message: Executing IL2CPU on assembly
16>Message: Kernel Base: Cosmos.System.Kernel
16>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\20-Platform\Cosmos.Platform.PC\bin\Debug\netstandard2.0\Cosmos.Platform.PC.dll
16>IL2CPU task took 00:00:01.2055269
16>Done building project "Cosmos.Platform.PC.csproj" -- FAILED.
18>------ Build started: Project: Cosmos.System2_Plugs, Configuration: Debug Any CPU ------
18>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2_Plugs\System\MathImpl.cs(391,26,391,39): warning CS0675: Bitwise-or operator used on a sign-extended operand; consider casting to a smaller unsigned type first
18>Cosmos.System2_Plugs -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2_Plugs\bin\Debug\netstandard2.0\Cosmos.System2_Plugs.dll
18>Message: Executing IL2CPU on assembly
18>Message: Kernel Base: Cosmos.System.Kernel
18>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.System2_Plugs\bin\Debug\netstandard2.0\Cosmos.System2_Plugs.dll
18>IL2CPU : error : No kernel found.
18>IL2CPU task took 00:00:04.1618242
18>Done building project "Cosmos.System2_Plugs.csproj" -- FAILED.
19>------ Build started: Project: Cosmos.Core_Plugs, Configuration: Debug Any CPU ------
17>Cosmos.Debug.Kernel.Plugs.Asm -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.Debug.Kernel.Plugs.Asm\bin\Debug\netstandard2.0\Cosmos.Debug.Kernel.Plugs.Asm.dll
20>------ Build started: Project: Cosmos.Plugs.TapRoot, Configuration: Debug Any CPU ------
20>Cosmos.Plugs.TapRoot -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\91-Plugs\Cosmos.Plugs.TapRoot\bin\Debug\netstandard2.0\Cosmos.Plugs.TapRoot.dll
20>Message: Executing IL2CPU on assembly
20>Message: Kernel Base: Cosmos.System.Kernel
20>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\91-Plugs\Cosmos.Plugs.TapRoot\bin\Debug\netstandard2.0\Cosmos.Plugs.TapRoot.dll
20>IL2CPU : error : No kernel found.
20>IL2CPU task took 00:00:01.2062353
20>Done building project "Cosmos.Plugs.TapRoot.csproj" -- FAILED.
21>------ Build started: Project: Cosmos.CPU_Plugs, Configuration: Debug Any CPU ------
21>C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\10-CPU\Cosmos.CPU_Plugs\System\StringImpl.cs(537,10,537,25): warning CS1030: #warning: 'TODO: implement'
21>Cosmos.CPU_Plugs -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\10-CPU\Cosmos.CPU_Plugs\bin\Debug\netstandard2.0\Cosmos.CPU_Plugs.dll
21>IL2CPU : error : No kernel found.
21>Message: Executing IL2CPU on assembly
21>Message: Kernel Base: Cosmos.System.Kernel
21>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\10-CPU\Cosmos.CPU_Plugs\bin\Debug\netstandard2.0\Cosmos.CPU_Plugs.dll
21>IL2CPU task took 00:00:01.6862378
21>Done building project "Cosmos.CPU_Plugs.csproj" -- FAILED.
22>------ Build started: Project: Cosmos.CPU_Asm, Configuration: Debug Any CPU ------
19>Cosmos.Core_Plugs -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Cosmos.Core_Plugs\bin\Debug\netstandard2.0\Cosmos.Core_Plugs.dll
22>Cosmos.CPU_Asm -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\10-CPU\Cosmos.CPU_Asm\bin\Debug\netstandard2.0\Cosmos.CPU_Asm.dll
22>Error : error occurred: System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
22>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
22>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
22>   at Cosmos.IL2CPU.IsolatedAssemblyLoadContext..ctor(IEnumerable`1 assemblyPaths) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\IsolatedAssemblyLoadContext.cs:line 43
22>   at Cosmos.IL2CPU.CompilerEngine..ctor(ICompilerEngineSettings aSettings) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 96
22>   at Cosmos.IL2CPU.Program.RunCompilerEngine(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 64
22>   at Cosmos.IL2CPU.Program.Run(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 47
22>IL2CPU task took 00:00:01.9526619
22>Done building project "Cosmos.CPU_Asm.csproj" -- FAILED.
23>------ Build started: Project: GuessKernelGen3, Configuration: Debug Any CPU ------
19>Error : error occurred: System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
19>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
19>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
19>   at Cosmos.IL2CPU.IsolatedAssemblyLoadContext..ctor(IEnumerable`1 assemblyPaths) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\IsolatedAssemblyLoadContext.cs:line 43
19>   at Cosmos.IL2CPU.CompilerEngine..ctor(ICompilerEngineSettings aSettings) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 96
19>   at Cosmos.IL2CPU.Program.RunCompilerEngine(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 64
19>   at Cosmos.IL2CPU.Program.Run(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 47
19>IL2CPU task took 00:00:02.5617309
19>Done building project "Cosmos.Core_Plugs.csproj" -- FAILED.
24>------ Build started: Project: TRKernel, Configuration: Debug Any CPU ------
24>TRKernel -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-TapRoot\Demo\bin\Debug\netstandard2.0\TRKernel.dll
23>GuessKernelGen3 -> C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-X86\50-Application\bin\Debug\netstandard2.0\GuessKernelGen3.dll
24>IL2CPU : error : No kernel found.
24>Message: Executing IL2CPU on assembly
23>Error : error occurred: System.IO.FileNotFoundException: Could not load file or assembly 'C:\Users\elkaa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.CPU.x86.dll'. The system cannot find the file specified.
23>File name: 'C:\Users\elkaa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.CPU.x86.dll'
23>   at System.Reflection.AssemblyName.nGetFileInformation(String s)
23>   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
23>   at System.Runtime.Loader.AssemblyLoadContext.GetAssemblyName(String assemblyPath)
23>   at Cosmos.IL2CPU.IsolatedAssemblyLoadContext..ctor(IEnumerable`1 assemblyPaths) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\IsolatedAssemblyLoadContext.cs:line 24
23>   at Cosmos.IL2CPU.CompilerEngine..ctor(ICompilerEngineSettings aSettings) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 96
23>   at Cosmos.IL2CPU.Program.RunCompilerEngine(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 64
23>   at Cosmos.IL2CPU.Program.Run(String[] aArgs, Action`1 aLogMessage, Action`1 aLogError) in C:\Users\elkaa\Desktop\Source\Cosmos\IL2CPU\source\Cosmos.IL2CPU\Program.cs:line 47
23>
23>
24>Message: Kernel Base: Cosmos.System.Kernel
24>Message: Checking target assembly: C:\Users\elkaa\Desktop\Source\Cosmos\Cosmos\source\Kernel-TapRoot\Demo\bin\Debug\netstandard2.0\TRKernel.dll
23>IL2CPU task took 00:00:02.9184878
23>Done building project "GuessKernelGen3.csproj" -- FAILED.
24>IL2CPU task took 00:00:02.5807616
24>Done building project "TRKernel.csproj" -- FAILED.
========== Build: 1 succeeded, 23 failed, 1 up-to-date, 0 skipped ==========`

**To Reproduce**
Describe any changes done to a clean kernel for an error to occur:
I just tried to install Cosmos.Build to every solution, because whenever I build the Kernel.sln solution, for every project in the solution it displays an error similar to this: `Build Failed: No Kernel Found:```

What does all of this mean? Do I build the Kernel.sln solution, the same way I would build a user kit project?

**Context**
Before posting please confirm that the following are in order
[ ] Both Cosmos VS Extensions are installed
[ ] The Cosmos nuget packages are installed

When I first installed the dev kit, I had to install Cosmos.Build, for every project in the solution and some other packages like Cosmos.HAL2, Cosmos.Core, etc.... When I first opened the solution, the Cosmos logo on every project in the solution wasn't there. 


Add any other context about the problem which might be helpful.


Also, how do I use and build with the dev kit? I am very familiar with the user kit, but how do I use the dev kit to modify, build and change something in Cosmos? Thx.

**Comment by quajak** [comment]
What project are you building? The devkit works very similar to the userkit in that you install it by running `install-VS2019.bat` and then any Cosmos projects you have will use the updated nuget packages. By modifying the source code used to build the devkit you can modify Cosmos. When modifying the devkit you usually use `Test.sln` since that allows you to run the tests.

**Comment by elkaamee326** [comment]
I am building Kernel.sln

**Comment by elkaamee326** [comment]
So, whenever I want to update the Cosmos Source I would use `Test.sln`?

**Comment by quajak** [comment]
Yes

**Comment by elkaamee326** [comment]
Okay, thanks.

**Comment by elkaamee326** [comment]
Also, what is `Kernel.sln` and the other solutions used for?

**Comment by quajak** [comment]
Kernel.sln currently doesnt have a real use. The Cosmos icon did not show up since these arnt actually Cosmos kernel projects but rather "just" C# library projects. Test.sln does not need the nuget packages, since all the code which is usually gotten from the nuget packages is built and included when you start the TestRunner.

**Comment by elkaamee326** [comment]
Okay, thx. Do I  just press the test runner button.

**Comment by quajak** [comment]
Yes
