### ISSUE TITLE
Exception: System.Exception;

### ISSUE THREAD

**Issue by uralgo2** [CosmosOS/Cosmos#1752]
Have you checked Github Issues for similar errors?
**Sure**
![Screenshot_1](https://user-images.githubusercontent.com/63842179/116996984-a4654f80-acf5-11eb-8d59-493972526738.png)

Post the exception returned by Visual Studio

Сборка начата…
1>------ Сборка начата: проект: Simple, Конфигурация: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: целевая платформа "netcoreapp2.0" больше не поддерживается и не будет получать обновления для системы безопасности в будущем. Дополнительные сведения о политике поддержки см. в https://aka.ms/dotnet-core-support.
1>Simple -> C:\Users\uralg\Documents\GitHub\SimpleOS\Simple\bin\Debug\netcoreapp2.0\cosmos\Simple.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\uralg\Documents\GitHub\SimpleOS\Simple\bin\Debug\netcoreapp2.0\cosmos\Simple.dll
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Int32  Interop+Kernel32.FindNLSStringEx(System.Char*, System.UInt32, System.Char*, System.Int32, System.Char*, System.Int32, System.Int32*, System.Void*, System.Void*, System.IntPtr).
1>  Called from :
1>System.Globalization.CompareInfo::Int32 FindString(UInt32, System.String, Int32, Int32, System.String, Int32, Int32, Int32*)
1>System.Globalization.CompareInfo::Int32 LastIndexOfCore(System.String, System.String, Int32, Int32, System.Globalization.CompareOptions)
1>System.Globalization.CompareInfo::Int32 LastIndexOf(System.String, System.String, Int32, Int32, System.Globalization.CompareOptions)
1>System.String::Int32 LastIndexOf(System.String, Int32, Int32, System.StringComparison)
1>System.String::Int32 LastIndexOf(System.String)
1>ML.Interpreter::Void Execute(System.String[])
1>Simple.Kernel::Void Run()
1>Cosmos.System.Kernel::Void Run()
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 617
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 770
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 264
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:01.4117744
1>Сборка проекта "Simple.csproj" завершена с ошибкой.
========== Сборка: успешно: 0, с ошибками: 1, без изменений: 0, пропущено: 0 ==========
Post the entire output log given by Visual Studio for the build

this error pop up on this code:
var strargs = line.Substring(line.IndexOf("(") + 1, line.LastIndexOf(")") - 1 - line.IndexOf("("));
var args = Utils.ParseArgs(strargs);
this.Functions[line.Split("(")[0]].Run(args);
utils.parseargs:
public static Variable[] ParseArgs(string args)
        {
            Regex reg =  new Regex(",(?=(([^']*'){2})*[^']*$)(?=(([^\"]*\"){2})*[^\"]*$)(?![^()]*\\))");
            List <Variable> vars = new List<Variable>();
            foreach (string arg in reg.Split(args))
            {
                vars.Add(new Variable(arg.TrimStart()));
            }
            return vars.ToArray();
        }
Variable:
 public class Variable
    {
        public Types type { get; }
        public string value { get; set; }
        public bool isConst { get; set; } = false;
        public Variable(string variable, bool isConst = false)
        {
            
            if (variable == Constants.TRUE || variable == Constants.FALSE)
                this.type = Types.BOOL;
            else if(!variable.StartsWith(Constants.DOUBLE_QUOTE) && !variable.StartsWith(Constants.SINGLE_QUOTE))
                this.type = Types.NUMBER;
            else if (variable.StartsWith(Constants.DOUBLE_QUOTE) || variable.StartsWith(Constants.SINGLE_QUOTE))
                this.type = Types.STRING;
            else if (variable.StartsWith(Constants.CLOSE_SQUARE) && variable.EndsWith(Constants.CLOSE_SQUARE))
                this.type = Types.ARRAY;
            if (variable.Contains("(") && variable[variable.Length - 1] == ')')
                this.value = Kernel.interpreter.Functions[variable.Split("(")[0]].Run(Utils.ParseArgs(variable.Substring(variable.IndexOf("(") + 1, variable.LastIndexOf(")") - 1 - variable.IndexOf("(")))).value;
            else
                this.value = variable;
            this.isConst = isConst;
        }
    }

[ ] Both Cosmos VS Extensions are installed
[ ] The Cosmos nuget packages are installed
last userkit

**Comment by cabfile** [comment]
there's a missing plug for whatever you're using. either ask someone for one (because i dont have any, sorry) or use something different. please see [this](http://www.gocosmos.org/docs/plugs/missing/).

**Comment by uralgo2** [comment]
@cabfile May be You give me anything must detailed guide for do this, please?

**Comment by MishaTY** [comment]
I will try to fix this issue. Looks like string.LastIndexOf() needs to be plugged.

**Comment by AcaiBerii** [comment]
This issue also occurs without plug errors

**Comment by valentinbreiz** [comment]
Cosmos Gen3 has replaced the IL2CPU-based Gen2 codebase, and `gen3` is now the default branch of this repository. This issue was filed against Gen2, which is no longer developed, so it is being closed as part of the Gen3 cutover (#3088).

If you still hit this on Gen3, please open a fresh issue. The compiler, the build pipeline and the debugging story are all different now, so a new report will get a far more useful answer than reviving this one. Start here: https://cosmosos.github.io/

Gen2 remains on the `gen2` branch, and this issue stays readable.
