### ISSUE TITLE
IL2CPU throws "System.NotImplementedException: OpCode 'Readonly' not implemented!"

### ISSUE THREAD

**Issue by virtualtoja** [CosmosOS/Cosmos#1773]
Have you checked Github Issues for similar errors?
Yes
**Exception**
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception: System.NotImplementedException: OpCode 'Readonly' not implemented!	ProgramManager	C:\Users\Tymon\source\repos\ProgramManager\ProgramManager\IL2CPU	1	

** VS Output Logs **
```
Build started...
1>------ Build started: Project: ProgramManager, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>C:\Users\Tymon\source\repos\ProgramManager\ProgramManager\FileSystem\FileSystem.cs(23,30,23,31): warning CS0168: The variable 'e' is declared but never used
1>ProgramManager -> C:\Users\Tymon\source\repos\ProgramManager\ProgramManager\bin\Debug\netcoreapp2.0\cosmos\ProgramManager.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\Tymon\source\repos\ProgramManager\ProgramManager\bin\Debug\netcoreapp2.0\cosmos\ProgramManager.dll
1>IL2CPU : error : Exception: System.NotImplementedException: OpCode 'Readonly' not implemented!
1>   at Cosmos.IL2CPU.ILOpCodes.OpNone.GetNumberOfStackPops(MethodBase aMethod) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCodes\OpNone.cs:line 164
1>   at Cosmos.IL2CPU.ILOpCode.InitStackAnalysis(MethodBase aMethod) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILOpCode.cs:line 302
1>   at Cosmos.IL2CPU.ILReader.ProcessMethod(MethodBase aMethod) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILReader.cs:line 446
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 639
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 770
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 264
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Development\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 200
1>IL2CPU task took 00:00:02.8537357
1>Done building project "ProgramManager.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```
**To Reproduce**
I dont know

**Screenshots**

**Context**
Before posting please confirm that the following are in order
[Yes] Both Cosmos VS Extensions are installed
[Yes] The Cosmos nuget packages are installed

My Code:
https://github.com/virtualtoja/ProgramManager

**Comment by virtualtoja** [comment]
Ok i fixed the issue by removing code.Split()
