### ISSUE TITLE
Exception: System.Exception: Error compiling method 'SystemVoidCosmosCore_AsmDelegateImplInvoke': System.Exception: Events with return type not yet supported!

### ISSUE THREAD

**Issue by AcaiBerii** [CosmosOS/Cosmos#1869]
Have you checked Github Issues for similar errors?
Yes

**Exception**
Error compiling method 'SystemVoidCosmosCore_AsmDelegateImplInvoke': System.Exception: Events with return type not yet supported!

** VS Output Logs **
```
Build started...
1>------ Build started: Project: DynamicCommandKernel, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
1>DynamicCommandKernel -> C:\Users\*****\source\repos\DynamicCommandKernel\DynamicCommandKernel\bin\Debug\netcoreapp2.0\cosmos\DynamicCommandKernel.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\*****\source\repos\DynamicCommandKernel\DynamicCommandKernel\bin\Debug\netcoreapp2.0\cosmos\DynamicCommandKernel.dll
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_INFO'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.FIELD_MAPPING'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.MethodIlOp'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.AssemblyFile'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Document'
1>Detecting fields for type 'IL2CPU.Debug.Symbols.Method'
1>IL2CPU : error : Exception: System.Exception: Error compiling method 'SystemVoidCosmosCore_AsmDelegateImplInvoke': System.Exception: Events with return type not yet supported!
1>   at Cosmos.Core_Asm.DelegateInvokeAsm.AssembleNew(Assembler aAssembler, Object aMethodInfo) in C:\Users\*****\Downloads\Cosmos\source\Cosmos.Core_Asm\Delegate\DelegateInvokeAsm.cs:line 23
1>   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\*****\Downloads\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 472 ---> System.Exception: Events with return type not yet supported!
1>   at Cosmos.Core_Asm.DelegateInvokeAsm.AssembleNew(Assembler aAssembler, Object aMethodInfo) in C:\Users\*****\Downloads\Cosmos\source\Cosmos.Core_Asm\Delegate\DelegateInvokeAsm.cs:line 23
1>   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\*****\Downloads\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 472
1>   --- End of inner exception stack trace ---
1>   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(_MethodInfo aMethod, List`1 aOpCodes) in C:\Users\*****\Downloads\IL2CPU\source\Cosmos.IL2CPU\AppAssembler.cs:line 547
1>   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\*****\Downloads\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 942
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Users\*****\Downloads\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 266
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\*****\Downloads\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 206
1>IL2CPU task took 00:00:06.5899203
1>Done building project "DynamicCommandKernel.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**To Reproduce**
Please look at https://github.com/BeriiDevelopment/DynamicCommandKernel

**Screenshots**

**Context**
Before posting please confirm that the following are in order
[x] Both Cosmos VS Extensions are installed
[x] In the NuGet Package Manager "Include prerelease" is selected
[x] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[x] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.
This is for my github project, DynamicCommandKernel. It seems as this may be part of operating a "Func<string, string[], bool>" (the return type is a bool). View https://github.com/BeriiDevelopment/DynamicCommandKernel/blob/main/DynamicCommandKernel/CommandActions.cs and https://github.com/BeriiDevelopment/DynamicCommandKernel/blob/main/DynamicCommandKernel/CommandSystem.cs :(

**Comment by zarlo** [comment]
a plug need to be made so add support to return types Cosmos\source\Cosmos.Core_Asm\Delegate\DelegateInvokeAsm.cs

**Comment by AcaiBerii** [comment]
> a plug need to be made so add support to return types Cosmos\source\Cosmos.Core_Asm\Delegate\DelegateInvokeAsm.cs

yesh

**Comment by AcaiBerii** [comment]
> a plug need to be made so add support to return types Cosmos\source\Cosmos.Core_Asm\Delegate\DelegateInvokeAsm.cs

Is the repo dead?
