### ISSUE TITLE
Il2CPU Can't find 'System.Runtime version 5.0.0.0'

### ISSUE THREAD

**Issue by MEMESCOEP** [CosmosOS/Cosmos#2106]
I'm getting build errors after upgrading to the newest release of the cosmos user kit (20220209). The problem doesn't go away even after a clean install.

Have you checked Github Issues for similar errors?
Yes.

**Exception**
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.	SussyOS2	C:\Users\andre\source\repos\SussyOS2\IL2CPU	1	

```
** VS Output Logs **
Post the entire output log given by Visual Studio for the build
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.	SussyOS2	C:\Users\andre\source\repos\SussyOS2\IL2CPU	1	



Build started...
1>------ Build started: Project: SussyOS2, Configuration: Debug Any CPU ------
1>SussyOS2 -> C:\Users\andre\source\repos\SussyOS2\bin\Debug\net5.0\SussyOS2.dll
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking target assembly: C:\Users\andre\source\repos\SussyOS2\bin\Debug\net5.0\SussyOS2.dll
1>IL2CPU : error : Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
1>File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
1>   at System.Reflection.RuntimeAssembly.GetExportedTypes()
1>   at System.Reflection.Assembly.get_ExportedTypes()
1>   at Cosmos.IL2CPU.CompilerEngine.LoadAssemblies() in C:\Users\andre\Downloads\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 291
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\andre\Downloads\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 141
1>
1>
1>IL2CPU task took 00:00:00.3640036
1>Done building project "SussyOS2.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

**To Reproduce**
I don't know why this is happening, I only ran the latest Cosmos User Kit (20220209)

**Screenshots**

**Context**
Before posting please confirm that the following are in order
[X] Both Cosmos VS Extensions are installed
[X] In the NuGet Package Manager "Include prerelease" is selected
[X] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[X] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.

**Comment by theLMGN** [comment]
At least for me personally, this issue occurred on a fresh Windows install.

**Comment by quajak** [comment]
It seems like the runtime cant find the .net 5 dlls. 
The workaround you wrote should not be possible since the error you posted above indicates that il2cpu failed to convert the dll into the iso. Are you always gettting the above mentioned error?
