### ISSUE TITLE
Cant build anything

### ISSUE THREAD

**Issue by vogon101** [CosmosOS/Cosmos#236]
After @charlesbetros latest commit I cant compile and kernel

```
Error: Exception: System.Exception: Error compiling method 'SystemVoidSystemIOStreamReaderDisposeSystemBoolean': System.Exception: Error interpreting stacktypes for IL_000A: And ---> System.NotImplementedException: And on types 'System.Boolean' and 'System.Int32' not yet implemented!
2>	   at Cosmos.IL2CPU.ILOpCodes.OpNone.DoInterpretStackTypes(Boolean& aSituationChanged) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCodes\OpNone.cs:line 748
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 399
2>	   --- End of inner exception stack trace ---
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 403
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
2>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
2>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
2>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
2>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
2>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
2>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 714
2>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 557
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 522 ---> System.Exception: Error interpreting stacktypes for IL_000A: And ---> System.NotImplementedException: And on types 'System.Boolean' and 'System.Int32' not yet implemented!
2>	   at Cosmos.IL2CPU.ILOpCodes.OpNone.DoInterpretStackTypes(Boolean& aSituationChanged) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCodes\OpNone.cs:line 748
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 399
2>	   --- End of inner exception stack trace ---
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 403
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
2>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
2>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
2>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
2>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
2>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
2>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 714
2>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 557
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 522
2>	   --- End of inner exception stack trace ---
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 529
2>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 944
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 256
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Freddie\Desktop\Programming\COSMOS\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
```

**Comment by vogon101** [comment]
@mterwoord @charlesbetros
