### ISSUE TITLE
Dup tries to pop more stuff from analytical stack than there is!

### ISSUE THREAD

**Issue by lukaandjelkovic** [CosmosOS/Cosmos#249]
Log:
```
4>	Error: Exception: System.Exception: Error compiling method 'SystemVoidKernelCommandsInputCommand': System.Exception: OpCode IL_014D: Dup tries to pop more stuff from analytical stack than there is!
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 369
4>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 714
4>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 557
4>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 514 ---> System.Exception: OpCode IL_014D: Dup tries to pop more stuff from analytical stack than there is!
4>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 369
4>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 714
4>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 557
4>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 514
4>	   --- End of inner exception stack trace ---
4>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\AppAssembler.cs:line 529
4>	   at Cosmos.IL2CPU.ILScanner.Assemble() in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 944
4>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 256
4>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Luka\Desktop\Cosmos-master\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
```
And there is code where it heappen:
```C#
public static void InputCommand()
        {
            Console.Write("D:/command>");
            comd = Console.ReadLine();
            comd = comd.ToLower();
            if (comd == "reboot") h.Power.Restart();
            else if (comd == "shutdown") h.Power.Shutdown();
            else if (comd == "echo")
            {
                Console.Write("Echo>");
                arg = Console.ReadLine();
                Console.WriteLine(arg);
            }
            else if (comd == "notepad")
            {
                System.CLI.Applications.Notepad();
            }
            else if (comd == "cls")
            {
                Console.Clear();
                Console.WriteLine("TriangleOS");
                Console.WriteLine("=============================");
            }
            else if (comd == "soundtest")
            {
                Console.Write("Frequency>");
                arg = Console.ReadLine();
                Console.Write("Duration>");
                optarg = Console.ReadLine();
                Console.Write("Eh, this isn't implemted right now.");
                //h.Multimedia.Speakers.CallSound(int.Parse(arg), int.Parse(optarg));
            }
            else if (comd == "boot")
            {
                Console.WriteLine("Starting TriangleOS.Drivers . . .");
                //ProcessManager.Process Audio = new ProcessManager.Process();
                //ProcessManager.Process Graphics = new ProcessManager.Process();
                //Graphics.ProcessThread = new System.Threading.Thread(
                h.Graphics.LowLevel.init();
                //);
                //ProcessManager.Process Mouse = new ProcessManager.Process();
                //Mouse.ProcessThread = new System.Threading.Thread(
                h.Mouse.InitMouse();
                //);
                //Graphics.Start();
                //Mouse.Start();
                //Audio.ProcessThread = new System.Threading.Thread(
                h.Multimedia.Speakers.IntailizeAudio();
                //);
                Kernel.GUI();
            }
            else if (comd == "cliboot")
            {
                System.CLI.Controls.TextBox Text = new System.CLI.Controls.TextBox();
                Text.x = 1;
                Text.y = 1;
                Text.length = 20;
                Text.DrawTextBox();
                Text.TypeInto();
                System.CLI.Controls.Button OK = new System.CLI.Controls.Button();
                OK.y = 22;
                OK.x = 1;
                OK.width = 6;
                OK.height = 1;
                OK.text = "OK";
                OK.DrawButton();
            }
            else if (comd == "calculator")
            {
                System.CLI.Applications.Calculator();
            }
            else if (comd == "cd")
            {
                h.Graphics.Console.ErrO("Impossible operation performed. Can't request I/O while it isn't running!");
            }
            else if (comd == "dir")
            {
                Console.WriteLine("This isn't folder. you can use <cd> to go up folder.");
            }
            else if (comd == "paint")
            {
                System.CLI.Applications.Paint();
            }
            else if (comd == "changelog")
            {
                Console.WriteLine("You are running version 0.0.3 Dev. Only Luka see the DEV!");
                Console.WriteLine("v0.0.2:");
                Console.WriteLine("Blue screen with cursor. not clearing.");
                Console.WriteLine("v0.0.3:");
                Console.WriteLine("Command Line Shell with Broken CLI, but working unresponsive GUI, but with DOS-like Shell. I/O, Audio, Multithreading, Shutdown doesn't work.");
            }
            else if (comd == "help")
            {
                Console.WriteLine("Copyright 2015 Thontelix TriangleOS. Special thanks to Cosmos .net ASM Compiler.");
                Console.WriteLine("type CHANGELOG to get version changes.");
                Console.WriteLine("How to use:");
                Console.WriteLine("After every typed command, press enter. the output of command will be detailed. If there is blinking bottom line cursor, then you need to input something, if it doesn't give any feedback, then its operating a activity. If you want GUI, type 'boot' and press enter.");
                Console.WriteLine("Commands:");
                Console.WriteLine("shutdown  - Gives you ability to safe turn off PC");
                Console.WriteLine("boot      - Boots you into TriangleOS");
                Console.WriteLine("reboot    - Reboots your PC");
                Console.WriteLine("cd        - Travel through directories");
                Console.WriteLine("dir       - Read content of directory");
                Console.WriteLine("echo      - Backs string you enter");
                Console.WriteLine("shutdown  - Backs string you enter");
                Console.WriteLine("soundtest - Speakers Drivers. Doesnt work for now");
                Console.WriteLine("help      - Gives you list of commands.");
                Console.WriteLine("paint     - Console Paint App. CAUTION:Not for epilepsy persons.");
            }
            else
            {
                Console.WriteLine("That command doesn't exist. :(");
            }
        }
```

**Comment by mterwoord** [comment]
Could you try to narrow down a bit? (ie, try to comment out more and more code until it stops erroring?)

**Comment by lukaandjelkovic** [comment]
it doesnt work even if its empty, but if i dont use it even if its empty it work.
So everything that is in function doesn't matter. Only if i dont call it then it work.

**Comment by charlesbetros** [comment]
How are you calling it? Can you provide more info?

**Comment by lukaandjelkovic** [comment]
It works now, magically.
