### ISSUE TITLE
/opt/cosmos/XSharp/DebugStub/ System.IO.IOException: Permission denied

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#2566]
dotnet build fails on new template project. chmod 777 all files of /opt/cosmos/XSharp/DebugStub/ manually fixes the issue.

IL2CPU : error : Exception: System.Exception: Error while generating output for file Init.xs [/home/valentinbreiz/Documents/perso/Cosmos/CosmosKernel1/CSharpProject.csproj]
   ---> System.UnauthorizedAccessException: Access to the path '/opt/cosmos/XSharp/DebugStub/Init.xs' is denied.
   ---> System.IO.IOException: Permission denied
     --- End of inner exception stack trace ---
     at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
     at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
     at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
     at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
     at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
     at System.IO.File.Open(String path, FileMode mode)
     at XSharp.AsmGenerator.Generate(String aSrcPathname) in /home/valentinbreiz/Documents/perso/Cosmos/XSharp/source/XSharp/XSharp/Gen1/AsmGenerator.cs:line 70
     --- End of inner exception stack trace ---
     at XSharp.AsmGenerator.Generate(String aSrcPathname) in /home/valentinbreiz/Documents/perso/Cosmos/XSharp/source/XSharp/XSharp/Gen1/AsmGenerator.cs:line 74
     at Cosmos.IL2CPU.CosmosAssembler.Initialize(Boolean enableVBE, String VBEResolution) in /home/valentinbreiz/Documents/perso/Cosmos/IL2CPU/source/Cosmos.IL2CPU/CosmosAssembler.cs:line 417
     at Cosmos.IL2CPU.CompilerEngine.Execute() in /home/valentinbreiz/Documents/perso/Cosmos/IL2CPU/source/Cosmos.IL2CPU/CompilerEngine.cs:line 197
  IL2CPU task took 00:00:00.4712221

Build FAILED.

IL2CPU : error : Exception: System.Exception: Error while generating output for file Init.xs [/home/valentinbreiz/Documents/perso/Cosmos/CosmosKernel1/CSharpProject.csproj]
    0 Warning(s)
    1 Error(s)

**Comment by AnErrupTion** [comment]
Did you try ``sudo chown valentinbreiz:valentinbreiz /opt``?

**Comment by zarlo** [comment]
changing the owner of the folder should fix it too
