### ISSUE TITLE
Could not load type 'Cosmos.Core.Multiboot.Multiboot2' from assembly 'Cosmos.Core'

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/Cosmos#2697]
When building a sample kernel from Linux:

```
(base) C:\home\valentinbreiz\Documents\perso\Cosmos\CosmosKernel2>dotnet build                 
MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  CosmosKernel2 -> /mnt/sdb/home/valentinbreiz/Documents/perso/Cosmos/CosmosKernel2/bin/cosmos/Debug/net6.0/CosmosKernel2.dll
  userkit: /opt/cosmos/
  Executing IL2CPU on assembly
  Kernel Base: Cosmos.System.Kernel
  Checking target assembly: /mnt/sdb/home/valendotnet new cosmosCSKernel -n {name}tinbreiz/Documents/perso/Cosmos/CosmosKernel2/bin/cosmos/Debug/net6.0/CosmosKernel2.dll
IL2CPU : warning : Loading plugs from assembly: Cosmos.Core_Asm, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983 [/mnt/sdb/home/valentinbreiz/Documents/perso/Cosmos/CosmosKernel2/CosmosKernel2.csproj]
IL2CPU : error : Exception: System.TypeLoadException: Could not load type 'Cosmos.Core.Multiboot.Multiboot2' from assembly 'Cosmos.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983'. [/mnt/sdb/home/valentinbreiz/Documents/perso/Cosmos/CosmosKernel2/CosmosKernel2.csproj]
     at System.Reflection.CustomAttribute._GetPropertyOrFieldData(RuntimeModule pModule, Byte** ppBlobStart, Byte* pBlobEnd, String& name, Boolean& bIsProperty, RuntimeType& type, Object& value)
     at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
     at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
     at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
     at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit)
     at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
     at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element, Boolean inherit)
     at Cosmos.IL2CPU.PlugManager.FindPlugImpls(IEnumerable`1 assemblies) in /mnt/sdb/home/valentinbreiz/Documents/perso/Cosmos/IL2CPU/source/Cosmos.IL2CPU/PlugManager.cs:line 84
     at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in /mnt/sdb/home/valentinbreiz/Documents/perso/Cosmos/IL2CPU/source/Cosmos.IL2CPU/ILScanner.cs:line 220
     at Cosmos.IL2CPU.CompilerEngine.Execute() in /mnt/sdb/home/valentinbreiz/Documents/perso/Cosmos/IL2CPU/source/Cosmos.IL2CPU/CompilerEngine.cs:line 189
  IL2CPU task took 00:00:00.3163921

Build FAILED.

IL2CPU : warning : Loading plugs from assembly: Cosmos.Core_Asm, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983 [/mnt/sdb/home/valentinbreiz/Documents/perso/Cosmos/CosmosKernel2/CosmosKernel2.csproj]
IL2CPU : error : Exception: System.TypeLoadException: Could not load type 'Cosmos.Core.Multiboot.Multiboot2' from assembly 'Cosmos.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983'. [/mnt/sdb/home/valentinbreiz/Documents/perso/Cosmos/CosmosKernel2/CosmosKernel2.csproj]
    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.37
```

**Comment by valentinbreiz** [comment]
It was due to remaining old Cosmos packages in /home/valentinbreiz/.nuget/packages/
They should also be removed

**Comment by zarlo** [comment]
to do that safely you have to clear the whole local cache as the dotnet cli does not offer a way to do it by package
