### ISSUE TITLE
Array.Sort gives missing plug error when it should not

### ISSUE THREAD

**Issue by 9xbt** [CosmosOS/Cosmos#2726]
#### Area of Cosmos - What area of Cosmos are we dealing with?
System2_Plugs

#### Expected Behaviour - What do you think that should happen?
`System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(System.Runtime.CompilerServices.QCallTypeHandle, System.IntPtr*, System.Int32, System.Runtime.CompilerServices.ObjectHandleOnStack)` should be plugged for `Array.Sort` to work properly

#### Actual Behaviour - What unexpectedly happens?
It's not

#### Reproduction - How did you get this error to appear?
Call `Array.Sort`

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest devkit

**Comment by 9xbt** [comment]
Here's the build log btw
```
Operación Compilar iniciada..
1>------ Operación Compilar iniciada: Proyecto: GoOS, configuración: Debug Any CPU ------
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\Commands\GoCodeInstaller.cs(3,7,3,13): warning CS0105: La directiva using para 'System' aparece previamente en este espacio de nombres
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\Commands\GoCodeInstaller.cs(5,7,5,16): warning CS0105: La directiva using para 'System.IO' aparece previamente en este espacio de nombres
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\Util\ConsoleUtil.cs(37,81,37,82): warning CS8632: La anotación para tipos de referencia que aceptan valores NULL solo debe usarse en el código dentro de un contexto de anotaciones "#nullable".
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\TextEditor.cs(64,15,64,16): warning CS8632: La anotación para tipos de referencia que aceptan valores NULL solo debe usarse en el código dentro de un contexto de anotaciones "#nullable".
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\Commands\dir.cs(53,30,53,31): warning CS0168: La variable 'e' se ha declarado pero nunca se usa
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\Commands\run.cs(42,32,42,42): warning CS0219: La variable 'keypressed' está asignada pero su valor nunca se usa
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\Dialogue.cs(19,102,19,113): warning CS0649: El campo 'Dialogue.infoIconRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\Apps\AppManager.cs(16,103,16,115): warning CS0649: El campo 'AppManager.clockIconRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\Apps\DesktopIcons.cs(13,104,13,117): warning CS0649: El campo 'DesktopIcons.folderIconRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\WindowManager.cs(221,105,221,119): warning CS0649: El campo 'WindowManager.warningIconRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\BetterConsole\BetterConsole.cs(22,27,22,36): warning CS0649: El campo 'BetterConsole.easterEgg' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\OOBE.cs(32,31,32,47): warning CS0649: El campo 'OOBE.setupComputerRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\OOBE.cs(17,31,17,46): warning CS0649: El campo 'OOBE.setupWelcomeRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\Apps\StartMenu.cs(18,106,18,121): warning CS0649: El campo 'StartMenu.shutdownIconRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\Apps\Welcome.cs(13,101,13,116): warning CS0649: El campo 'Welcome.welcomeImageRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\OOBE.cs(41,31,41,44): warning CS0649: El campo 'OOBE.setupFinalRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\Apps\StartMenu.cs(15,102,15,114): warning CS0649: El campo 'StartMenu.userImageRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\Apps\AppManager.cs(13,103,13,115): warning CS0649: El campo 'AppManager.gtermIconRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\OOBE.cs(35,31,35,44): warning CS0649: El campo 'OOBE.setupThemeRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\WindowManager.cs(15,103,15,111): warning CS0649: El campo 'WindowManager.mouseRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\Window.cs(17,117,17,138): warning CS0649: El campo 'Window.closeButtonPressedRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\OOBE.cs(38,31,38,42): warning CS0649: El campo 'OOBE.setupResRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\Window.cs(11,109,11,123): warning CS0649: El campo 'Window.closeButtonRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\Window.cs(14,115,14,134): warning CS0649: El campo 'Window.closeButtonHoverRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\Apps\StartMenu.cs(21,103,21,115): warning CS0649: El campo 'StartMenu.gtermIconRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\LoadingDialogue.cs(13,102,13,113): warning CS0649: El campo 'LoadingDialogue.drumIconRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\OOBE.cs(26,31,26,46): warning CS0649: El campo 'OOBE.setupSupportRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\OOBE.cs(20,31,20,42): warning CS0649: El campo 'OOBE.setupTOURaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\MemoryWatch.cs(14,105,14,119): warning CS0649: El campo 'MemoryWatch.warningIconRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\OOBE.cs(23,31,23,41): warning CS0649: El campo 'OOBE.setupUARaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\OOBE.cs(29,31,29,43): warning CS0649: El campo 'OOBE.setupUserRaw' nunca se asigna y siempre tendrá el valor predeterminado null
1>C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\GUI\Input.cs(237,21,237,28): warning CS0414: El campo 'Input.scrollY' está asignado pero su valor nunca se usa
1>GoOS -> C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\bin\Debug\net6.0\GoOS.dll
1>Executing IL2CPU on assembly
1>Kernel Base: Cosmos.System.Kernel
1>Checking target assembly: C:\Users\Eric\Documents\GitHub\GoOS-Fork\GoOS\bin\Debug\net6.0\GoOS.dll
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.Core_Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.Core_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.Debug.Kernel.Plugs.Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.System2_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : error : Exception: System.Exception:
1>Native code encountered, plug required.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Void  System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(System.Runtime.CompilerServices.QCallTypeHandle, System.IntPtr*, System.Int32, System.Runtime.CompilerServices.ObjectHandleOnStack)(Plug Signature: System_Void__System_RuntimeTypeHandle_CreateInstanceForAnotherGenericParameter_System_Runtime_CompilerServices_QCallTypeHandle__System_IntPtr#__System_Int32__System_Runtime_CompilerServices_ObjectHandleOnStack_ ).
1>  Static: True
1>  Assembly: System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
1>  Called from:
1>System.RuntimeTypeHandle::System.Object CreateInstanceForAnotherGenericParameter(System.RuntimeType, System.RuntimeType)
1>System.Collections.Generic.ArraySortHelper`1[System.String]::System.Collections.Generic.IArraySortHelper`1[System.String] CreateArraySortHelper()
1>System.Collections.Generic.ArraySortHelper`1[System.String]::Void .cctor()
1>System.Collections.Generic.ArraySortHelper`1[System.String]
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\Eric\Documents\GitHub\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 562
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\Eric\Documents\GitHub\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 752
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Users\Eric\Documents\GitHub\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 270
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Eric\Documents\GitHub\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 189
1>IL2CPU task took 00:00:01.8657145
1>Compilación del proyecto "GoOS.csproj" terminada -- ERROR.
========== Compilación: 0 correcto, 1 erróneo, 0 actualizado, 0 omitido ==========
========= Compilar se inició en 3:02 PM y tomó 02,918 segundos ==========
```

**Comment by zarlo** [comment]
```System.RuntimeTypeHandle.CreateInstanceForAnotherGenericParameter(System.Runtime.CompilerServices.QCallTypeHandle, System.IntPtr*, System.Int32, System.Runtime.CompilerServices.ObjectHandleOnStack)``` is the method that needs to be pluged

**Comment by 9xbt** [comment]
Yeah

**Comment by Hasnain12340** [comment]
I think yes maybe?
