### ISSUE TITLE
System.IndexOutOfRangeException on ILScanner when instantiating a LiteDatabase object of the LiteDB nugget package

### ISSUE THREAD

**Issue by Guillermo-Santos** [CosmosOS/Cosmos#2858]
Second of the three issues mencioned on #2857 .

This one throws with an index out of Range Exception.
**Exception**
Post the exception returned by Visual Studio
```
Build started at 11:12 PM...
1>------ Build started: Project: CosmosKernel1, Configuration: Debug Any CPU ------
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>CosmosKernel1 -> D:\source\repos\Zaphyros\CosmosKernel1\bin\Debug\net6.0\CosmosKernel1.dll
1>Executing IL2CPU on assembly
1>Kernel Base: Cosmos.System.Kernel
1>Checking target assembly: D:\source\repos\Zaphyros\CosmosKernel1\bin\Debug\net6.0\CosmosKernel1.dll
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.Core_Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.Core_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.Debug.Kernel.Plugs.Asm, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Loading plugs from assembly: Cosmos.System2_Plugs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=5ae71220097cb983
1>IL2CPU : warning : Invalid plug method! Target method not found. : A0SystemIOTextReaderA2CosmosSystem_PlugsSystemConsoleImplGetOrCreateReader
1>IL2CPU : error : Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
1>   at Cosmos.IL2CPU.ILScanner.ScanType(Type aType) in D:\source\CosmosOS-Dev\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 650
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in D:\source\CosmosOS-Dev\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 755
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in D:\source\CosmosOS-Dev\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 270
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in D:\source\CosmosOS-Dev\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 186
1>IL2CPU task took 00:00:00.6579357
1>Done building project "CosmosKernel1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 11:12 PM and took 02.039 seconds ==========

```
**Visual Studio Output Logs**
Post the entire output log given by Visual Studio for the build

**How To Reproduce**
Describe any changes done to a clean kernel for this error to occur.
Add the [LiteDB](https://www.nuget.org/packages/LiteDB) nugget package
```csproj
<PackageReference Include="LiteDB" Version="5.0.17" />
```
Instantiate a LiteDatabase Object
``` csharp
var database = new LiteDatabase("0:\\System\\Register.db");
```
Build
**Screenshots**

**Context**
Before posting please confirm that the following are in order
- [x] Both Cosmos VS Extensions are installed
- [x] In the NuGet Package Manager "Include prerelease" is selected
- [x] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
- [x] The Cosmos NuGet packages are installed

Add any other context about the problem which might be helpful.

**Comment by Guillermo-Santos** [comment]
Using dev kit
