### ISSUE TITLE
IL2CPU not compiling

### ISSUE THREAD

**Issue by moonway-dev** [CosmosOS/Cosmos#3062]
I updated from userkit to devkit by building it from source code and when compiling I started getting an error. 
Tell me what the problem is, please.

```
1>Executing IL2CPU on assembly
1>Kernel Base: Cosmos.System.Kernel
1>Checking target assembly: D:\moonway-dev\ScrewOS\ScrewOS\bin\Debug\net6.0\ScrewOS.dll
1>IL2CPU : error : Exception: System.Exception: Native code encountered, plug required. Check build output for more information.
1>  DO NOT REPORT THIS AS A BUG.
1>  Please see http://www.gocosmos.org/docs/plugs/missing/
1>  Need plug for: System.Void  System.String..ctor(System.ReadOnlySpan`1<System.Char>)(Plug Signature: System_Void__System_String__ctor_System_ReadOnlySpan_1_System_Char__ ).
1>  Static: False
1>  Assembly: System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
1>  Called from:
1>System.Runtime.CompilerServices.DefaultInterpolatedStringHandler::System.String ToStringAndClear()
1>Cosmos.System.Kernel::Void Start()
1>
1>
1>
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\moonway\Desktop\kernel\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 562
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\moonway\Desktop\kernel\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 751
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod, IEnumerable`1 plugsAssemblies) in C:\Users\moonway\Desktop\kernel\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 270
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\moonway\Desktop\kernel\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 187
1>IL2CPU task took 00:00:02.5580459
```

**Comment by MishaProductions** [comment]
Installing Cosmos.Plugs in nuget should fix the issue.
