### ISSUE TITLE
IL2CPU Compiler Exception: System.Exception: Error compiling method 'SystemStringSystemLinqEnumerableFirstOrDefaultSystemStringSystemCollectionsGenericIEnumerable1SystemString': System.Exception: Error interpreting stacktypes for IL_0001: Brtrue ---> System.Exception: Invalid type in PopTypes! (Type = 'System.Collections.Generic.

### ISSUE THREAD

**Issue by Ray1015** [CosmosOS/Cosmos#311]
I Searched All Over The Web For This!

Code: 
```C#
TypedCommand.Split(' ').FirstOrDefault();
```

**Comment by ImaBrokeDude** [comment]
Can you post full error and stack trace in the comments?

**Comment by Ray1015** [comment]
Stack Trace Here:
```
2>	Error: Exception: System.Exception: Error compiling method 'SystemStringSystemLinqEnumerableFirstOrDefaultSystemStringSystemCollectionsGenericIEnumerable1SystemString': System.Exception: Error interpreting stacktypes for IL_0001: Brtrue ---> System.Exception: Invalid type in PopTypes! (Type = 'System.Collections.Generic.IEnumerable`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
2>	   at Cosmos.IL2CPU.ILOpCodes.OpBranch.DoInterpretStackTypes(Boolean& aSituationChanged) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCodes\OpBranch.cs:line 112
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 399
2>	   --- End of inner exception stack trace ---
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 403
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
2>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
2>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 712
2>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 555
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 520 ---> System.Exception: Error interpreting stacktypes for IL_0001: Brtrue ---> System.Exception: Invalid type in PopTypes! (Type = 'System.Collections.Generic.IEnumerable`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
2>	   at Cosmos.IL2CPU.ILOpCodes.OpBranch.DoInterpretStackTypes(Boolean& aSituationChanged) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCodes\OpBranch.cs:line 112
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 399
2>	   --- End of inner exception stack trace ---
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 403
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(ILOpCode xNextOpCode, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 456
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretInstruction(Int32 aPosition, IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 450
2>	   at Cosmos.IL2CPU.ILOpCode.DoInterpretNextInstructionStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 432
2>	   at Cosmos.IL2CPU.ILOpCode.InterpretStackTypes(IDictionary`2 aOpCodes, Stack`1 aStack, Boolean& aSituationChanged, Int32 aMaxRecursionDepth) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILOpCode.cs:line 409
2>	   at Cosmos.IL2CPU.AppAssembler.InterpretInstructionsToDetermineStackTypes(List`1 aCurrentGroup) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 712
2>	   at Cosmos.IL2CPU.AppAssembler.EmitInstructions(MethodInfo aMethod, List`1 aCurrentGroup, Boolean& emitINT3) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 555
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 520
2>	   --- End of inner exception stack trace ---
2>	   at Cosmos.IL2CPU.AppAssembler.ProcessMethod(MethodInfo aMethod, List`1 aOpCodes) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\AppAssembler.cs:line 527
2>	   at Cosmos.IL2CPU.ILScanner.Assemble() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 941
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 257
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
```

**Comment by Ray1015** [comment]
The Full Error Is Right In The Title.

**Comment by Ray1015** [comment]
I Wanted To Upload The File But GitHub Didn't Let Me.

**Comment by charlesbetros** [comment]
Linq isn't supported yet.

**Comment by Ray1015** [comment]
What Is Linq?

**Comment by charlesbetros** [comment]
The FirstOrDefault() is a Linq extension. Try doing something like
var parts = TypedCommands.Splt(' ');
if (parts.Length > 0)
{
    string command = parts[0];
}

**Comment by ImaBrokeDude** [comment]
LINQ = Language-Intergrated Query

**Comment by Ray1015** [comment]
Do I Make A Plug?

**Comment by Ray1015** [comment]
It Worked! Do I Close This Now?

**Comment by charlesbetros** [comment]
You can leave it open. It's still an issue we need to track. It won't be done any time soon though.

**Comment by mterwoord** [comment]
@charlesbetros So this is purely  related to usage of Linq and therefore interfaces?

**Comment by Ray1015** [comment]
No.

**Comment by Ray1015** [comment]
Console Only.
