### ISSUE TITLE
After I do anything to the sample code it wont work.

### ISSUE THREAD

**Issue by Sphunts01** [CosmosOS/Cosmos#367]
I start with a brand new project and run it, it works fine, I edit it, it doesn't work, there is one error after I run it, `Error occurred while invoking IL2CPU` I tried reopening project reinstalling cosmos, making a new project, (after I edit it has the same error) and restarting my computer multiple times. Still same error. Here is the exact log:

`1>------ Build started: Project: SEE-C, Configuration: Debug Any CPU ------
1>  SEE-C -> c:\users\kids\documents\visual studio 2015\Projects\SEE-C\SEE-C\bin\Debug\SEE-C.dll
2>------ Build started: Project: SEE-CBoot, Configuration: Debug x86 ------
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:c:\users\kids\documents\visual studio 2015\Projects\SEE-C\SEE-C\bin\Debug\SEE-CBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:c:\users\kids\documents\visual studio 2015\Projects\SEE-C\SEE-C\bin\Debug\SEE-C.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:c:\users\kids\documents\visual studio 2015\Projects\SEE-C\SEE-C\bin\Debug\SEE-CBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll" "References:C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:c:\users\kids\documents\visual studio 2015\Projects\SEE-C\SEE-C\bin\Debug\SEE-C.dll" "References:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" 
2>	Working directory = 'c:\users\kids\documents\visual studio 2015\Projects\SEE-C\SEE-C\bin\Debug\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Executing IL2CPU on assembly
2>	Plug found: 'System.RuntimeType'
2>	Plug found: 'System.OutOfMemoryException'
2>	Plug found: 'System.Double'
2>	Plug found: 'System.Delegate'
2>	Plug found: 'System.Array'
2>	Plug found: 'System.Buffer'
2>	Plug found: 'System.Enum'
2>	Plug found: 'System.EventHandler'
2>	Plug found: 'System.Exception'
2>	Plug found: 'System.MulticastDelegate'
2>	Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
2>	Plug found: 'System.Math'
2>	Plug found: 'System.String'
2>	Plug found: 'System.Diagnostics.Debugger'
2>	Plug found: 'System.Byte'
2>	Plug found: 'System.Environment'
2>	Plug found: 'System.GC'
2>	Plug found: 'System.Int16'
2>	Plug found: 'System.Int32'
2>	Plug found: 'System.Int64'
2>	Plug found: 'System.IntPtr'
2>	Plug found: 'System.Number'
2>	Plug found: 'System.Object'
2>	Plug found: 'System.Single'
2>	Plug found: 'System.SR'
2>	Plug found: 'System.UInt16'
2>	Plug found: 'System.UInt32'
2>	Plug found: 'System.UInt64'
2>	Plug found: 'System.Threading.Interlocked'
2>	Plug found: 'System.Runtime.InteropServices.SafeHandle'
2>	Plug found: 'System.Resources.ResourceManager'
2>	Plug found: 'System.Net.IPAddress'
2>	Plug found: 'System.Net.SocketAddress'
2>	Plug found: 'System.Globalization.NumberFormatInfo'
2>	Plug found: 'System.Drawing.Color'
2>	Plug found: 'System.Drawing.SR'
2>	Plug found: 'System.Security.CodeAccessSecurityEngine'
2>	Plug found: 'System.RuntimeType+RuntimeTypeCache'
2>	Plug found: 'System.RuntimeTypeHandle'
2>	Plug found: 'System.SByte'
2>	Plug found: 'System.UIntPtr'
2>	Plug found: 'System.Security.Cryptography.Utils'
2>	Plug found: 'System.Globalization.CultureInfo'
2>	Plug found: 'Microsoft.Win32.RegistryKey'
2>	Plug found: 'Cosmos.Core.CPU'
2>	Plug found: 'Cosmos.IL2CPU.GCImplementation'
2>	Plug found: 'Cosmos.Core.IOPortBase'
2>	Plug found: 'Cosmos.Debug.Kernel.Debugger'
2>	Plug found: 'System.Char'
2>	Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
2>	Plug found: 'System.Random'
2>	Plug found: 'System.Console'
2>	Plug found: 'System.Type'
2>	Plug found: 'System.Threading.Monitor'
2>	Plug found: 'System.Text.DecoderFallback'
2>	Plug found: 'System.Text.EncoderFallback'
2>	Plug found: 'System.Text.ASCIIEncoding'
2>	Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
2>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Void  System.Threading.Thread.SleepInternal(System.Int32).
2>	 Called from :
2>	System.Threading.Thread::Void Sleep(Int32)
2>	SEE_C.Process+sys::Void Halt(System.String)
2>	SEE_C.Kernel::Void Run()
2>	Cosmos.System.Kernel::Void Run()
2>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 525
2>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 670
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Data\Sources\OpenSource\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
2>	Loaded assemblies: 
2>	C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
2>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
2>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	c:\users\kids\documents\visual studio 2015\Projects\SEE-C\SEE-C\bin\Debug\SEE-C.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
2>	C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
2>	C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
2>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
2>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
2>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
2>	C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.DebugStub.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSharp.Nasm.dll
2>	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
2>	C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:00.7808868
2>Done building project "SEE-CBoot.Cosmos" -- FAILED.
2>
Build has been canceled.`

The part it is failing on every time is: `C:\Users\Kids\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
2>	Errorred`

If you would like to see the code to check just ask.

I cant figure this out, please help.

**Comment by Sphunts01** [comment]
Nevermind
