### ISSUE TITLE
Can't retrieve interface maps on generic interfaces on arrays.

### ISSUE THREAD

**Issue by ghost** [CosmosOS/Cosmos#438]
When compiling a text-user-interface toolkit that wraps around System.Console (called ConsoleDraw) for Cosmos/Memphis, I get the following IL2CPU exception in my build log.

```
Error: Exception: System.ArgumentException: Interface maps for generic interfaces on arrays cannot be retrived.
1>     at System.RuntimeType.GetInterfaceMap(Type ifaceType)
1>     at Cosmos.IL2CPU.ILScanner.ScanType(Type aType) in C:\Users\mikey\Documents\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 643
1>     at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\mikey\Documents\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 673
1>     at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\mikey\Documents\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 245
1>     at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\mikey\Documents\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 252
1>  
```

I have not modified ConsoleDraw and looking through the code I see no use of interfaces. Memphis itself compiles just fine without ConsoleDraw.

**Comment by jp2masa** [comment]
Replaced by https://github.com/CosmosOS/IL2CPU/issues/15
