### ISSUE TITLE
Opcode 'stobj' not implemented error

### ISSUE THREAD

**Issue by pshah123** [CosmosOS/Cosmos#72]
I just installed the devkit and compiled Cosmos.Hardware. I'm using a dll reference in my project and I'm trying to use the PCSpeaker class to beep. However, whenever I build I get a System.NotImplementedException. Help? I have included my code and the full error below.

<b>Kernel.cs</b>
```csharp
using System;
using System.Text;
using Sys = Cosmos.System;
using Cosmos.Hardware;

namespace CosmosKernel2
{
    public class Kernel : Sys.Kernel
    {
        string username;
        string input;
        protected override void BeforeRun()
        {
            Console.WriteLine("Welcome to CyOS");
        }

        protected override void Run()
        {
            Console.WriteLine("Username:");
            username = Console.ReadLine();
            Console.Clear();
            Console.WriteLine("Hello " + username + "");
            Console.WriteLine("Press any key to continue.");
            input = Console.ReadLine();
            Console.Clear();
            PCSpeaker speaker = new PCSpeaker();
            while (username.Length > -1)
            {
                Console.Write("Users/" + username + "/:>");
                input = Console.ReadLine();
                
                switch (input.Substring(0, 3))
                {
                    case "cls": Console.Clear(); break;
                    case "sta": Console.WriteLine("Reading GREEN"); break;
                    case "pri": Console.WriteLine(input.Substring(6)); break;
                    case "ope": Console.WriteLine("No filesystem was found."); break;
                    case "dir": Console.WriteLine("No filesystem was found."); break;
                    case "lis": Console.WriteLine("No filesystem was found."); break;
                    case "bee": speaker.beep(); break;
                    case "qui": speaker.nosound(); break;
                    case "run": Console.WriteLine("System Exception: No filesystem was found."); break;
                    default: if (input == "") break; else Console.WriteLine("Unable to execute command. Error: Command Does Not Exist"); break;
                }

            }
        }
    }
}
```

<b>Error from Build Output</b>
```
1>------ Build started: Project: CosmosKernel2, Configuration: Debug Any CPU ------
1>CSC : warning CS1762: A reference was created to embedded interop assembly 'c:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Interop.VixCOM.dll' because of an indirect reference to that assembly created by assembly 'c:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.VSDebugEngine.dll'. Consider changing the 'Embed Interop Types' property on either assembly.
1>CSC : warning CS1762: A reference was created to embedded interop assembly 'c:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Interop.VixCOM.dll' because of an indirect reference to that assembly created by assembly 'c:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Vestris.VMWareLib.dll'. Consider changing the 'Embed Interop Types' property on either assembly.
1>C:\Users\Priansh\Documents\Visual Studio 2013\Projects\CosmosKernel2\CosmosKernel2\ACPI.cs(22,30,22,36): warning CS0414: The field 'CosmosKernel2.ACPI.SCI_EN' is assigned but its value is never used
1>  CosmosKernel2 -> C:\Users\Priansh\Documents\Visual Studio 2013\Projects\CosmosKernel2\CosmosKernel2\bin\Debug\CosmosKernel2.dll
2>------ Build started: Project: CosmosKernel2Boot, Configuration: Debug x86 ------
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Error occurred while invoking IL2CPU.
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error : Exception: System.NotImplementedException: OpCode 'Stobj' not implemented! Encountered in method Boolean TryGetValue(System.String, Int32 ByRef)
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.ILOpCodes.OpType.GetNumberOfStackPops(MethodBase aMethod) in c:\Users\Priansh\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.IL2CPU\ILOpCodes\OpType.cs:line 48
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.ILOpCode.InitStackAnalysis(MethodBase aMethod) in c:\Users\Priansh\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.IL2CPU\ILOpCode.cs:line 296
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.ILReader.ProcessMethod(MethodBase aMethod) in c:\Users\Priansh\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.IL2CPU\ILReader.cs:line 407
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in c:\Users\Priansh\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 537
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.ILScanner.ScanQueue() in c:\Users\Priansh\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 662
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in c:\Users\Priansh\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.IL2CPU\ILScanner.cs:line 249
2>C:\Program Files (x86)\MSBuild\Cosmos\Cosmos.targets(31,5): error :    at Cosmos.IL2CPU.CompilerEngine.Execute() in c:\Users\Priansh\Downloads\Cosmos-master\Cosmos-master\source\Cosmos.IL2CPU\CompilerEngine.cs:line 238
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Message: Executing IL2CPU on assembly
2>	Message: Plug found: 'Microsoft.Win32.RegistryKey'
2>	Message: Plug found: 'System.Array'
2>	Message: Plug found: 'System.Byte'
2>	Message: Plug found: 'System.Char'
2>	Message: Plug found: 'System.Delegate'
2>	Message: Plug found: 'System.Double'
2>	Message: Plug found: 'System.Drawing.Color'
2>	Message: Plug found: 'System.Drawing.SR'
2>	Message: Plug found: 'System.Enum'
2>	Message: Plug found: 'System.Environment'
2>	Message: Plug found: 'System.GC'
2>	Message: Plug found: 'System.Globalization.CultureInfo'
2>	Message: Plug found: 'System.Globalization.NumberFormatInfo'
2>	Message: Plug found: 'System.Int16'
2>	Message: Plug found: 'System.Int32'
2>	Message: Plug found: 'System.Int64'
2>	Message: Plug found: 'System.IntPtr'
2>	Message: Plug found: 'System.Net.IPAddress'
2>	Message: Plug found: 'System.Net.SocketAddress'
2>	Message: Plug found: 'System.Number'
2>	Message: Plug found: 'System.Object'
2>	Message: Plug found: 'System.Resources.ResourceManager'
2>	Message: Plug found: 'System.RuntimeType'
2>	Message: Plug found: 'System.RuntimeType+RuntimeTypeCache'
2>	Message: Plug found: 'System.RuntimeTypeHandle'
2>	Message: Plug found: 'System.Security.CodeAccessSecurityEngine'
2>	Message: Plug found: 'System.Runtime.CompilerServices.RuntimeHelpers'
2>	Message: Plug found: 'System.Runtime.InteropServices.SafeHandle'
2>	Message: Plug found: 'System.SByte'
2>	Message: Plug found: 'System.Security.Cryptography.Utils'
2>	Message: Plug found: 'System.Single'
2>	Message: Plug found: 'System.SR'
2>	Message: Plug found: 'System.String'
2>	Message: Plug found: 'System.Threading.Interlocked'
2>	Message: Plug found: 'System.UInt16'
2>	Message: Plug found: 'System.UInt32'
2>	Message: Plug found: 'System.UInt64'
2>	Message: Plug found: 'System.Diagnostics.Debugger'
2>	Message: Plug found: 'System.Math'
2>	Message: Plug found: 'System.Buffer'
2>	Message: Plug found: 'System.EventHandler'
2>	Message: Plug found: 'System.Exception'
2>	Message: Plug found: 'System.MulticastDelegate'
2>	Message: Plug found: 'System.OutOfMemoryException'
2>	Message: Plug found: 'Cosmos.Core.CPU'
2>	Message: Plug found: 'Cosmos.IL2CPU.GCImplementation'
2>	Message: Plug found: 'Cosmos.Core.IOPortBase'
2>	Message: Plug found: 'Cosmos.Debug.Kernel.Debugger'
2>	Message: Plug found: 'System.Collections.Generic.Dictionary`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'
2>	Message: Plug found: 'System.Random'
2>	Message: Plug found: 'System.Text.DecoderFallback'
2>	Message: Plug found: 'System.Text.EncoderFallback'
2>	Message: Plug found: 'System.Text.ASCIIEncoding'
2>	Message: Plug found: 'System.Console'
2>	Message: Plug found: 'System.Text.InternalDecoderBestFitFallbackBuffer'
2>	Message: Plug found: 'System.Threading.Monitor'
2>	Message: Plug found: 'System.Type'
2>	Message: Loaded assemblies: 
2>	Message: C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Build.Common.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Common.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Assembler.dll
2>	Message: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
2>	Message: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.IL2CPU.Plugs.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	Message: C:\Users\Priansh\Documents\Visual Studio 2013\Projects\CosmosKernel2\CosmosKernel2\bin\Debug\CosmosKernel2.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Mono.Cecil.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\System.Data.SQLite.dll
2>	Message: C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
2>	Message: C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\DapperExtensions.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\SQLinq.dll
2>	Message: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll
2>	Message: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
2>	Message: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
2>	Message: C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSC.exe
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\XSharp.Nasm.dll
2>	Message: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Debug.Kernel.dll
2>	Message: C:\Users\Priansh\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.HAL.dll
2>	Message: C:\Users\Priansh\Documents\Visual Studio 2013\Projects\CosmosKernel2\CosmosKernel2\bin\Debug\Cosmos.Hardware.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:02.6240657
2>Done building project "CosmosKernel2Boot.Cosmos" -- FAILED.
2>
Build has been canceled.
```

**Comment by mterwoord** [comment]
Sorry for the late response...

Would you be willing to help us fix this?
It's a bug in our IL interpreter..

**Comment by ZackCDLVI** [comment]
I've also run into several "not implanted" IL errors. I'm assuming this has something to do with the recent Z-machine implantation.

**Comment by mterwoord** [comment]
Which Z-machine implementation?

The bug is in our IL interpreter, and isn't too hard to fix. We could guide you through the process....

**Comment by pshah123** [comment]
That'd be great! Fair warning, I'm a bit lost on "IL interpreter". Is that
what interprets methods + etc into machine language?

On Fri, Apr 17, 2015 at 12:06 PM, Matthijs ter Woord <
notifications@github.com> wrote:

> Which Z-machine implementation?
>
> The bug is in our IL interpreter, and isn't too hard to fix. We could
> guide you through the process....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CosmosOS/Cosmos/issues/72#issuecomment-94017088>.
>



-- 
-*Priansh Shah*

**Comment by ZackCDLVI** [comment]
Oh, I thought it had something to do with it. Never mind!

**Comment by mterwoord** [comment]
@phsah123 IL looks for example like this:
IL_0001: ldc.i4.3  (Loads a constant int32 value of 4 on to the stack)
IL_0002: ldc.i4.2
IL_0003: add

offset 3 ha no way of knowing (without looking back) what types it has to add (it could be 2 bytes, but also 2 decimals). The il interpreter "interprets" the previous instructions (and branches etc are also handled) to see what operand types the compiler needs to use..

The situation for stobj is not yet implemented.

**Comment by PathogenDavid** [comment]
So I decided to take a stab at this problem since I've been meaning to check out Cosmos in detail for some time and had some free time today.

Fixing Stobj for GetNumberOfStackPops and GetNumberOfStackPushes was simple enough. However, after I fixed those two things I got an issue of a missing plug for RuntimeTypeHandle::CreateInstanceForAnotherGenericParameter.

This method is called from [EqualityComparer<T>.CreateComparer](https://github.com/dotnet/coreclr/blob/cbf46fb0b6a0b209ed1caf4a680910b383e68cba/src/mscorlib/src/System/Collections/Generic/EqualityComparer.cs#L42) when a System.Collections.Generic.Dictionary is constructed.

Of course, it might seem confusing that there is a Dictionary getting created considering pshah123's code doesn't use the Dictionary class. Well, apparently after you go over 6 cases in a switch statement on a string, the C# compiler changes it into a Dictionary lookup instead.

Anyway, I tracked down CreateInstanceForAnotherGenericParameter's implementation in CoreCLR to [CreateInstanceForGenericType](https://github.com/dotnet/coreclr/blob/cbf46fb0b6a0b209ed1caf4a680910b383e68cba/src/vm/reflectioninvocation.cpp#L748), and it is a bit of a doozy.

I'm pretty sure the whole thing boils down to allocating and constructing a GenericEqualityComparer<string> (in our case), but it isn't immediately obvious to me how to best do the same thing in Cosmos. I wanted to post in here and see if anyone wanted to point me in the right direction before I dive down this rabbit hole.

**Comment by PathogenDavid** [comment]
And on a semi-related note: Is there a way to get changes I've made to Cosmos into my installed user kit without restarting Visual Studio every time? Whenever I make a change to IL2CPU, I end up closing all my instances of Visual Studio and running install.bat again. Not sure if I missed something in the documentation or the workflow there is just a bit tedious right now.

**Comment by mterwoord** [comment]
@PathogenDavid Good work. Can you send a pull request for the GetNumberOfStackPops and GetNumberOfStackPushes changes?

Most likely the CreateCompiler code uses reflection to do its magic, which won't work for sure on cosmos.
Maybe we could make special cases in EqualityComparer.CreateComparer for the main types (String, numeric types, etc)

@PathogenDavid Would you be interested in helping us out? We could really use some lower-level people. We have some humps in the compiler currently and once we're past those, we could really move forward again...

**Comment by PathogenDavid** [comment]
@mterwoord
Sure, do know though that I have no idea if stobj is working since I couldn't compile+run the code without the plug. The pull request is #77.

That is what I was thinking as well. It wouldn't be as ideal, but it certainly works. I'll give it a try sometime this week and report back.

I'm definitely interested in helping out, but I can't really promise any consistent effort on my part for the time being. My free time is a bit sporadic these days.

**Comment by mterwoord** [comment]
@PathogenDavid If you're interested in helping, please add me on skype (same handle), and I'll get you going. At first, we could use help on getting the PR's reviewed...
