### ISSUE TITLE
Plug required for System.String.InternalUseRandomizedHashing()

### ISSUE THREAD

**Issue by thosakwe** [CosmosOS/Cosmos#732]
Hi, getting a super cryptic error. Typically I try to diagnose these things, and contribute helpful feedback, but I can't figure out where I'm going wrong. Here's the IL2CPU output:

```
1>------ Build started: Project: TobeOS, Configuration: Debug Any CPU ------
1>TobeOS -> C:\Users\thosa\Source\CS\TobeOS\TobeOS\bin\Debug\netstandard1.5\TobeOS.dll
2>------ Build started: Project: TobeOSBoot, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Core". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>	Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\thosa\Source\CS\TobeOS\TobeOS\bin\Debug\net462\TobeOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Common.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Common.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\thosa\Source\CS\TobeOS\TobeOS\bin\Debug\netstandard1.5\TobeOS.dll" 
2>C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(36,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:True" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\thosa\Source\CS\TobeOS\TobeOS\bin\Debug\net462\TobeOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Common.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Common.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.dll" "References:C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\thosa\Source\CS\TobeOS\TobeOS\bin\Debug\netstandard1.5\TobeOS.dll" 
2>	Working directory = 'C:\Users\thosa\Source\CS\TobeOS\TobeOS\bin\Debug\net462\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : StackCorruptionDetectionLevel
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Loaded : AdditionalSearchDirs
2>	Loaded : AdditionalReferences
2>	Executing IL2CPU on assembly
2>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Boolean  System.String.InternalUseRandomizedHashing().
2>	 Called from :
2>	System.String::Boolean UseRandomizedHashing()
2>	System.Collections.HashHelpers::Void .cctor()
2>	System.Collections.HashHelpers
2>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 548
2>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 694
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\ILScanner.cs:line 255
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\jpedr\Documents\Projects\Cosmos-origin-master-2\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
2>	Loaded assemblies: 
2>	C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Common.dll
2>	C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.Common.dll
2>	C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.Core.dll
2>	C:\Users\thosa\Source\CS\TobeOS\TobeOS\bin\Debug\net462\Cosmos.Core.Plugs.Asm.dll
2>	C:\Users\thosa\Source\CS\TobeOS\TobeOS\bin\Debug\net462\Cosmos.Core.Plugs.dll
2>	C:\Users\thosa\Source\CS\TobeOS\TobeOS\bin\Debug\net462\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>	C:\Users\thosa\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\Cosmos.System.dll
2>	C:\Users\thosa\Source\CS\TobeOS\TobeOS\bin\Debug\net462\Cosmos.System.Plugs.dll
2>	C:\Users\thosa\Source\CS\TobeOS\TobeOS\bin\Debug\net462\TobeOS.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='False',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:01.2146608
2>Done building project "TobeOSBoot.Cosmos" -- FAILED.
2>
========== Build: 1 succeeded or up-to-date, 1 failed, 0 skipped ==========
```

The thing is, IL2CPU isn't telling me where I'm calling the `UseRandomizedHashing()` function.
Here's my code: https://github.com/thosakwe/TobeOS

I was thinking that using generics (dictionary/list) was causing this, so I got rid of them. Turns out that wasn't the problem.

**Comment by zarlo** [comment]
UseRandomizedHashing() must use native code

**Comment by thosakwe** [comment]
Yes, I am aware. Not sure what's calling it, though. The error message doesn't point to a call location where I can remove it.

**Comment by djlw78** [comment]
Huh. Since Cosmos is in another major update migration most of my code stops at IL2CPU. For many random and unneeded reasons.

**Comment by thosakwe** [comment]
Culprit was `Dictionary`.
