### ISSUE TITLE
Error occurred while invoking IL2CPU.

### ISSUE THREAD

**Issue by SalahEddineBC** [CosmosOS/Cosmos#843]
#### Area of Cosmos - What area of Cosmos are we dealing with?
IL2CPU

#### Expected Behaviour - What do you think that should happen?
i guess that .net standard2.0 is not supported yet  

Restauration des packages NuGet...
Pour empêcher NuGet de restaurer les packages lors de la génération, ouvrez la boîte de dialogue des options de Visual Studio, cliquez sur le nœud Gestionnaire de package et désactivez Autoriser NuGet à télécharger les packages manquants lors de la génération.
1>------ Début de la génération : Projet : EsiOSBoot, Configuration : Debug Any CPU ------
1>	Invoking il2cpu.exe "DebugEnabled:False" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\bachi\source\repos\EsiOS\EsiOS\bin\Debug\net462\EsiOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\bachi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\bachi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\bachi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\bachi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\bachi\source\repos\EsiOS\EsiOS\bin\Debug\netstandard2.0\EsiOS.dll" 
1>C:\Users\bachi\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(39,5): error : Error occurred while invoking IL2CPU.
1>	Executing command line "C:\Users\bachi\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:False" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\bachi\source\repos\EsiOS\EsiOS\bin\Debug\net462\EsiOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\bachi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\bachi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\bachi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\bachi\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\bachi\source\repos\EsiOS\EsiOS\bin\Debug\netstandard2.0\EsiOS.dll" 
1>	Working directory = 'C:\Users\bachi\source\repos\EsiOS\EsiOS\bin\Debug\net462\'
1>	Loaded : DebugEnabled
1>	Loaded : StackCorruptionDetectionEnabled
1>	Loaded : DebugMode
1>	Loaded : StackCorruptionDetectionLevel
1>	Loaded : TraceAssemblies
1>	Loaded : DebugCom
1>	Loaded : UseNAsm
1>	Loaded : OutputFilename
1>	Loaded : EnableLogging
1>	Loaded : EmitDebugSymbols
1>	Loaded : IgnoreDebugStubAttribute
1>	Loaded : References
1>	Loaded : AdditionalSearchDirs
1>	Loaded : AdditionalReferences
1>	Executing IL2CPU on assembly
1>	Error: Exception: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Le fichier spÃ©cifiÃ© est introuvable.
1>	File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
1>	   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
1>	   at System.Reflection.RuntimeAssembly.GetExportedTypes()
1>	   at System.Reflection.Assembly.get_ExportedTypes()
1>	   at Cosmos.IL2CPU.CompilerEngine.LoadAssemblies() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 351
1>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 151
1>	Loaded assemblies: 
1>	C:\Users\bachi\source\repos\EsiOS\EsiOS\bin\Debug\net462\Cosmos.Core.Plugs.Asm.dll
1>	C:\Users\bachi\source\repos\EsiOS\EsiOS\bin\Debug\net462\Cosmos.Core.Plugs.dll
1>	C:\Users\bachi\source\repos\EsiOS\EsiOS\bin\Debug\net462\Cosmos.Debug.Kernel.Plugs.Asm.dll
1>	C:\Users\bachi\source\repos\EsiOS\EsiOS\bin\Debug\net462\Cosmos.System.Plugs.dll
1>	C:\Users\bachi\source\repos\EsiOS\EsiOS\bin\Debug\net462\EsiOS.dll
1>	Errorred
1>	IL2CPU invoked with DebugMode='Source', DebugEnabled='False',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
1>	IL2CPU task took 00:00:00.3180694
1>Génération du projet "EsiOSBoot.Cosmos" terminée -- ÉCHEC.
1>
========== Génération : 0 a réussi, 1 a échoué, 1 mis à jour, 0 a été ignoré ==========

**Comment by fanoI** [comment]
It means that you have not installed thing correctly... you have Net Core 2.0 and Net Stand 2.0 installed as Visual Studio workloads?

**Comment by SalahEddineBC** [comment]
yes i can see .net stand 2.0 in the list of available frameworks but i got the same error.

**Comment by hwoadministrator** [comment]
Yeah, I have a problem too. But it does not show a lot of it. It show only : Severity	Code	Description	Project	File	Line	Suppression State
Error occurred while invoking IL2CPU.	hwo-i1Boot	C:\Users\ASUS\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets	70

**Comment by Project-Magenta** [comment]
Go into build output

**Comment by hwoadministrator** [comment]
![image](https://user-images.githubusercontent.com/25245598/34456179-d7a4dae6-edc2-11e7-9997-8bf3b6ffc58c.png)
First time I build it working. Second time I build it making errors.

**Comment by jp2masa** [comment]
I think that is the same as #810.

**Comment by quajak** [comment]
Is the problem still present?
