### ISSUE TITLE
Exception: System.ArgumentException: 'this' type cannot be an interface itself.

### ISSUE THREAD

**Issue by ghost** [CosmosOS/Cosmos#922]
#### Area of Cosmos - What area of Cosmos are we dealing with?
IL2CPU

#### Expected Behaviour - What do you think that should happen?
Build the project to ISO Image File

#### Actual Behaviour - What unexpectedly happens?
Exception: System.ArgumentException: 'this' type cannot be an interface itself.

#### Reproduction - How did you get this error to appear?
Build / Rebuild Solution

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos DevKit v106027 (Commit #912 )

```
1>------ Build started: Project: Sharpware, Configuration: Debug Any CPU ------
1>Sharpware -> E:\Projects\Sharpware\Source Code\Sharpware\bin\Debug\netcoreapp2.0\Sharpware.dll
1>Invoking IL2CPU.exe "KernelPkg:" "EnableDebug:True" "EnableStackCorruptionDetection:True" "StackCorruptionDetectionLevel:MethodFooters" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "OutputFilename:E:\Projects\Sharpware\Source Code\Sharpware\bin\Debug\netcoreapp2.0\Sharpware.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:E:\Projects\Sharpware\Source Code\Sharpware\bin\Debug\netcoreapp2.0\Sharpware.dll" "References:C:\Users\Dennise\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll" "References:C:\Users\Dennise\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll" "References:C:\Users\Dennise\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Dennise\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll" "AssemblySearchDirs:C:\Users\Dennise\AppData\Roaming\Cosmos User Kit\Kernel\\" "AssemblySearchDirs:C:\Users\Dennise\.nuget\packages\cosmos.common\2018.3.2\lib\netstandard2.0\\" "AssemblySearchDirs:C:\Users\Dennise\.nuget\packages\cosmos.core\2018.3.2\lib\netstandard2.0\\" "AssemblySearchDirs:C:\Users\Dennise\.nuget\packages\cosmos.debug.kernel\2018.3.2\lib\netstandard2.0\\" "AssemblySearchDirs:C:\Users\Dennise\.nuget\packages\cosmos.hal2\2018.3.2\lib\netstandard2.0\\" "AssemblySearchDirs:C:\Users\Dennise\.nuget\packages\cosmos.system2\2018.3.2\lib\netstandard2.0\\" "AssemblySearchDirs:C:\Users\Dennise\.nuget\packages\il2cpu.api\2018.3.2\lib\netstandard2.0\\" "AssemblySearchDirs:C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\\"
1>Message: Executing IL2CPU on assembly
1>Message: Kernel Base: Cosmos.System.Kernel
1>Message: Checking Reference: E:\Projects\Sharpware\Source Code\Sharpware\bin\Debug\netcoreapp2.0\Sharpware.dll
1>Message:   Exists
1>Message: Checking Reference: C:\Users\Dennise\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll
1>Message:   Exists
1>Message: Checking Reference: C:\Users\Dennise\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll
1>Message:   Exists
1>Message: Checking Reference: C:\Users\Dennise\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
1>Message:   Exists
1>Message: Checking Reference: C:\Users\Dennise\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll
1>Message:   Exists
1>Message: Loaded assemblies:
1>IL2CPU : error : Exception: System.ArgumentException: 'this' type cannot be an interface itself.
1>   at System.RuntimeTypeHandle.VerifyInterfaceIsImplemented(RuntimeTypeHandle handle, RuntimeTypeHandle interfaceHandle)
1>   at System.RuntimeType.GetInterfaceMap(Type ifaceType)
1>   at Cosmos.IL2CPU.ILScanner.GetUltimateBaseMethod(MethodBase aMethod, Type[] aMethodParams, Type aCurrentInspectedType) in E:\Projects\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 828
1>   at Cosmos.IL2CPU.ILScanner.GetMethodUID(MethodBase aMethod, Boolean aExact) in E:\Projects\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 897
1>   at Cosmos.IL2CPU.ILScanner.ProcessInstructions(List`1 aOpCodes) in E:\Projects\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 331
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in E:\Projects\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 641
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in E:\Projects\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 772
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in E:\Projects\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 251
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in E:\Projects\CosmosOS\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 168
1>Message: E:\Projects\Sharpware\Source Code\Sharpware\bin\Debug\netcoreapp2.0\Sharpware.dll
1>Message: C:\Users\Dennise\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll
1>Message: C:\Users\Dennise\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll
1>Message: C:\Users\Dennise\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
1>Message: C:\Users\Dennise\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll
1>Done building project "Sharpware.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by Arawn-Davies** [comment]
This happens with the current Gen2 version of the compiler, which will be fixed soon efore Gen3 is released for use.

Can you try cleaning and re-building the project? This shouldn't need to be done but it's a workaround for the time being

**Comment by valentinbreiz** [comment]
@Arawn-Davies same error. Cleaned the project and same issue.
