### ISSUE TITLE
IL2CPU - Build stopped working: System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by Norech** [CosmosOS/Cosmos#944]
#### Area of Cosmos - What area of Cosmos are we dealing with?
IL2CPU

#### Expected Behaviour - What do you think that should happen?
It should build

#### Actual Behaviour - What unexpectedly happens?
It was working, and without reasons it stopped working yesterday.
```
1>------ Début de la génération : Projet : AswideDebug, Configuration : Debug Any CPU ------
1>AswideDebug -> H:\Dev\Languages\CSharp\Aswide\AswideDebug\bin\Debug\netstandard1.5\AswideDebug.dll
2>------ Début de la génération : Projet : AswideSystem, Configuration : Debug Any CPU ------
2>AswideSystem -> H:\Dev\Languages\CSharp\Aswide\AswideSystem\bin\Debug\netstandard1.5\AswideSystem.dll
3>------ Début de la génération : Projet : Aswide, Configuration : Debug Any CPU ------
3>Aswide -> H:\Dev\Languages\CSharp\Aswide\Aswide\bin\Debug\netstandard1.5\Aswide.dll
4>------ Début de la génération : Projet : AswideBoot, Configuration : Debug Any CPU ------
4>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:H:\Dev\Languages\CSharp\Aswide\Aswide\bin\Debug\net462\AswideBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:H:\Dev\Languages\CSharp\Aswide\Aswide\bin\Debug\netstandard1.5\Aswide.dll" "References:C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" 
4>C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(39,5): error : Error occurred while invoking IL2CPU.
4>	Executing command line "C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:H:\Dev\Languages\CSharp\Aswide\Aswide\bin\Debug\net462\AswideBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:H:\Dev\Languages\CSharp\Aswide\Aswide\bin\Debug\netstandard1.5\Aswide.dll" "References:C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" 
4>	Working directory = 'H:\Dev\Languages\CSharp\Aswide\Aswide\bin\Debug\net462\'
4>	Loaded : DebugEnabled
4>	Loaded : StackCorruptionDetectionEnabled
4>	Loaded : DebugMode
4>	Loaded : StackCorruptionDetectionLevel
4>	Loaded : TraceAssemblies
4>	Loaded : DebugCom
4>	Loaded : UseNAsm
4>	Loaded : OutputFilename
4>	Loaded : EnableLogging
4>	Loaded : EmitDebugSymbols
4>	Loaded : IgnoreDebugStubAttribute
4>	Loaded : References
4>	Loaded : AdditionalSearchDirs
4>	Loaded : AdditionalReferences
4>	Executing IL2CPU on assembly
4>	Error: Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'AswideSystem, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Le fichier spÃ©cifiÃ© est introuvable.
4>	   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
4>	   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
4>	   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
4>	   at System.Reflection.RuntimeModule.ResolveMethod(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
4>	   --- End of inner exception stack trace ---
4>	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
4>	   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
4>	   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
4>	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
4>	   at Cosmos.Debug.Symbols.ModuleExtensions.Invoke[T](MethodInfo method, Module module, Object[] args) in C:\Users\Administrator\Cosmos\source\Cosmos.Debug.Symbols\ModuleExtensions.cs:line 35
4>	   at Cosmos.Debug.Symbols.ModuleExtensions.ResolveMethod(Module module, Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) in C:\Users\Administrator\Cosmos\source\Cosmos.Debug.Symbols\ModuleExtensions.cs:line 22
4>	   at Cosmos.IL2CPU.ILReader.ProcessMethod(MethodBase aMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILReader.cs:line 331
4>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 565
4>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 694
4>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
4>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
4>	Loaded assemblies: 
4>	H:\Dev\Languages\CSharp\Aswide\Aswide\bin\Debug\netstandard1.5\Aswide.dll
4>	C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll
4>	C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
4>	C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
4>	C:\Users\Alexis\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
4>	Errorred
4>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
4>	IL2CPU task took 00:00:00.8498826
4>Génération du projet "AswideBoot.Cosmos" terminée -- ÉCHEC.
4>
========== Génération : 3 a réussi, 1 a échoué, 0 mis à jour, 0 a été ignoré ==========
```

#### Reproduction - How did you get this error to appear?
I made a solution with 3 projects (+ Boot project), and I linked them like this:

##### Aswide (User Ring)
 - All 'Cosmos User Kit\Kernel' DLLs
 - Default NetStandard.Library
 - AswideDebug (System Ring)
 - AswideSystem (System Ring)

##### AswideSystem (System Ring)
 - All 'Cosmos User Kit\Kernel' DLLs
 - Default NetStandard.Library
 - AswideDebug (System Ring)
 - AswideSystem (System Ring)

##### AswideDebug (System Ring)
 - All 'Cosmos User Kit\Kernel' DLLs
 - Default NetStandard.Library

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
User Kit 2017 09 28

**Comment by jp2masa** [comment]
Try using the Dev Kit.

**Comment by zarlo** [comment]
check if AswideSystem is been copied to the output folder as its the DLL cant be found

**Comment by Norech** [comment]
@zarlo If you mean copied in the bin/Debug/netstandard1.5 of AswideSystem and Aswide, it is.
