### ISSUE TITLE
Error occurred while invoking IL2CPU when building/starting project

### ISSUE THREAD

**Issue by PixxlMaster** [CosmosOS/Cosmos#995]
[Solved]

#### Area of Cosmos - What area of Cosmos are we dealing with?
Building/IL2CPU

#### Expected Behaviour - What do you think that should happen?
Build/start the project in a Vmware window

#### Actual Behaviour - What unexpectedly happens?
The build fails and I get the error "Error occurred while invoking IL2CPU." (and I get sad)

#### Reproduction - How did you get this error to appear?
I simply build/start the project

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit
I am using the latest User Kit

Output:
1>------ Build started: Project: SimplexOS, Configuration: Debug Any CPU ------
1>SimplexOS -> C:\Users\Oliver Halenius\source\repos\SimplexOS\SimplexOS\bin\Debug\netstandard1.5\SimplexOS.dll
2>------ Build started: Project: SimplexOSBoot, Configuration: Debug Any CPU ------
2>	Invoking il2cpu.exe "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Oliver Halenius\source\repos\SimplexOS\SimplexOS\bin\Debug\net462\SimplexOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Oliver Halenius\source\repos\SimplexOS\SimplexOS\bin\Debug\netstandard1.5\SimplexOS.dll" 
2>C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Build\VSIP\Cosmos.targets(39,5): error : Error occurred while invoking IL2CPU.
2>	Executing command line "C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Build\IL2CPU\IL2CPU.exe" "DebugEnabled:True" "StackCorruptionDetectionEnabled:False" "StackCorruptionDetectionLevel:" "DebugMode:Source" "TraceAssemblies:" "DebugCom:1" "UseNAsm:True" "OutputFilename:C:\Users\Oliver Halenius\source\repos\SimplexOS\SimplexOS\bin\Debug\net462\SimplexOSBoot.asm" "EnableLogging:True" "EmitDebugSymbols:True" "IgnoreDebugStubAttribute:False" "References:C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll" "References:C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll" "References:C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll" "References:C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll" "References:C:\Users\Oliver Halenius\source\repos\SimplexOS\SimplexOS\bin\Debug\netstandard1.5\SimplexOS.dll" 
2>	Working directory = 'C:\Users\Oliver Halenius\source\repos\SimplexOS\SimplexOS\bin\Debug\net462\'
2>	Loaded : DebugEnabled
2>	Loaded : StackCorruptionDetectionEnabled
2>	Loaded : DebugMode
2>	Loaded : StackCorruptionDetectionLevel
2>	Loaded : TraceAssemblies
2>	Loaded : DebugCom
2>	Loaded : UseNAsm
2>	Loaded : OutputFilename
2>	Loaded : EnableLogging
2>	Loaded : EmitDebugSymbols
2>	Loaded : IgnoreDebugStubAttribute
2>	Loaded : References
2>	Loaded : AdditionalSearchDirs
2>	Loaded : AdditionalReferences
2>	Executing IL2CPU on assembly
2>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Void  System.Environment._Exit(System.Int32).
2>	 Called from :
2>	System.Environment::Void Exit(Int32)
2>	SimplexOS.Kernel::Void PerformAction()
2>	SimplexOS.Kernel::Void Run()
2>	Cosmos.System.Kernel::Void Run()
2>	   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 548
2>	   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 694
2>	   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\ILScanner.cs:line 255
2>	   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\Administrator\Cosmos\source\Cosmos.IL2CPU\CompilerEngine.cs:line 197
2>	Loaded assemblies: 
2>	C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.Asm.dll
2>	C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core.Plugs.dll
2>	C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
2>	C:\Users\Oliver Halenius\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System.Plugs.dll
2>	C:\Users\Oliver Halenius\source\repos\SimplexOS\SimplexOS\bin\Debug\netstandard1.5\SimplexOS.dll
2>	Errorred
2>	IL2CPU invoked with DebugMode='Source', DebugEnabled='True',StackCorruptionDetectionLevel='{NULL}', TraceAssemblies='{NULL}', IgnoreDebugStub='False'
2>	IL2CPU task took 00:00:04.2245753
2>Done building project "SimplexOSBoot.Cosmos" -- FAILED.
2>
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Also, the code is barely changed from the "standard" code and I don´t think It works even with the standard code...

I have also tried restarting Visual Studio

**Comment by PixxlMaster** [comment]
Never mind, I looked through the output and detected that the issue was that I used Enviroment.Exit(1);
